runtime:
  volume_data_dir: /tmp/arhat/data
  container_namespace: container.arhat.dev

  endpoints:
    image:
      address: /run/containerd/containerd.sock
      dial_timeout: 10s
      action_timeout: 2m
    runtime:
      address: /run/containerd/containerd.sock
      dial_timeout: 10s
      action_timeout: 2m

connectivity:
  server:
    address: aranya.example.com:12443
    dial_timeout: 20s
    tls:
      cert: /etc/arhat/cert.pem
      key: /etc/arhat/key.pem
