#
# NOTICE: podman runtime is currently not supported, this configuration is just for reference
#
agent:
  log:
    level: 5
    dir: /var/log/arhat/
  features:
    allow_host_exec: false
    allow_host_attach: false
    allow_host_log: false
    allow_host_port_forward: false
  node:
    timers:
      status_sync_interval: 10m
  pod:
    max_pod_count: 10
    timers:
      status_sync_interval: 60s

runtime:
  data_dir: /tmp/arhat/data
  management_namespace: container.arhat.dev

  pause_image: k8s.gcr.io/pause:3.1
  pause_command: /pause

  # runtime with podman doesn't need any endpoints (it's embedded into arhat)
  endpoints:
    image:
      dial_timeout: 10s
      action_timeout: 2m
    runtime:
      dial_timeout: 10s
      action_timeout: 2m

connectivity:
  # mqtt_config:
  grpc_config:
    server:
      address: arhat-podman.example.com:12443
      dial_timeout: 20s
    tls:
      cert: /etc/arhat/cert.pem
      key: /etc/arhat/key.pem
