#
# NOTICE: containerd runtime is currently not supported, this configuration is just for reference
#
agent:
  log:
    level: 5
    dir: /var/log/arhat/
  features:
    allow_host_exec: false
  node:
    timers:
      status_sync_interval: 10m
  pod:
    max_pod_count: 10
    timers:
      status_sync_interval: 60s

runtime:
  root_dir: /tmp/arhat/data
  management_namespace: container.arhat.dev

  pause_image: k8s.gcr.io/pause:3.1
  pause_command: /pause

  endpoints:
    image:
      address: unix:///run/containerd/containerd.sock
      dial_timeout: 10s
      action_timeout: 2m
    runtime:
      address: unix:///run/containerd/containerd.sock
      dial_timeout: 10s
      action_timeout: 2m

connectivity:
  # mqtt_config:
  grpc_config:
    server:
      address: arhat-containerd.example.com:12443
      dial_timeout: 20s
    tls:
      cert: /etc/arhat/cert.pem
      key: /etc/arhat/key.pem
