agent:
  log:
    level: 5
    dir: /var/log/arhat/
  features:
    allow_host_exec: false
  timers:
    node_status_sync_interval: 100m
    pod_status_sync_interval: 60s

runtime:
  volume_data_dir: /tmp/arhat/data
  management_namespace: container.arhat.dev

  pause_image: k8s.gcr.io/pause:3.1
  pause_command: /pause

  endpoints:
    image:
      dial_timeout: 10s
      action_timeout: 2m
    runtime:
      dial_timeout: 10s
      action_timeout: 2m

connectivity:
  server:
    address: aranya.example.com:12443
    dial_timeout: 20s
    tls:
      cert: /etc/arhat/cert.pem
      key: /etc/arhat/key.pem
