runtime:
  volume_data_dir: /tmp/arhat/data
  management_namespace: container.arhat.dev

  pause_image: k8s.gcr.io/pause:3.1
  pause_command: /pause

  endpoints:
    image:
      address: unix:///var/run/docker.sock
      dial_timeout: 10s
      action_timeout: 2m
    runtime:
      address: unix:///var/run/docker.sock
      dial_timeout: 10s
      action_timeout: 2m

connectivity:
  server:
    address: aranya.example.com:12443
    dial_timeout: 20s
    tls:
      cert: /etc/arhat/cert.pem
      key: /etc/arhat/key.pem
