// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connectivity.proto

package connectivity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Ignoring public import of PodInfo from pod.proto

// Ignoring public import of PodIdentity from pod.proto

// Ignoring public import of PodCmd from pod.proto

// Ignoring public import of PodCreateOptions from pod.proto

// Ignoring public import of PodDeleteOptions from pod.proto

// Ignoring public import of PodListOptions from pod.proto

// Ignoring public import of PodLogOptions from pod.proto

// Ignoring public import of PodExecOptions from pod.proto

// Ignoring public import of PodPortForwardOptions from pod.proto

// Ignoring public import of PodData from pod.proto

// Ignoring public import of Phase from pod.proto

// Ignoring public import of ActionType from pod.proto

// Ignoring public import of DeviceInfo from device.proto

type Message struct {
	SessionId uint64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Completed bool   `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*Message_DeviceInfo
	//	*Message_PodInfo
	//	*Message_PodData
	Message              isMessage_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_connectivity_d587803b39197f99, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *Message) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type isMessage_Message interface {
	isMessage_Message()
}

type Message_DeviceInfo struct {
	DeviceInfo *DeviceInfo `protobuf:"bytes,11,opt,name=device_info,json=deviceInfo,proto3,oneof"`
}

type Message_PodInfo struct {
	PodInfo *PodInfo `protobuf:"bytes,12,opt,name=pod_info,json=podInfo,proto3,oneof"`
}

type Message_PodData struct {
	PodData *PodData `protobuf:"bytes,13,opt,name=pod_data,json=podData,proto3,oneof"`
}

func (*Message_DeviceInfo) isMessage_Message() {}

func (*Message_PodInfo) isMessage_Message() {}

func (*Message_PodData) isMessage_Message() {}

func (m *Message) GetMessage() isMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Message) GetDeviceInfo() *DeviceInfo {
	if x, ok := m.GetMessage().(*Message_DeviceInfo); ok {
		return x.DeviceInfo
	}
	return nil
}

func (m *Message) GetPodInfo() *PodInfo {
	if x, ok := m.GetMessage().(*Message_PodInfo); ok {
		return x.PodInfo
	}
	return nil
}

func (m *Message) GetPodData() *PodData {
	if x, ok := m.GetMessage().(*Message_PodData); ok {
		return x.PodData
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_DeviceInfo)(nil),
		(*Message_PodInfo)(nil),
		(*Message_PodData)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// message
	switch x := m.Message.(type) {
	case *Message_DeviceInfo:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeviceInfo); err != nil {
			return err
		}
	case *Message_PodInfo:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PodInfo); err != nil {
			return err
		}
	case *Message_PodData:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PodData); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Message has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 11: // message.device_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeviceInfo)
		err := b.DecodeMessage(msg)
		m.Message = &Message_DeviceInfo{msg}
		return true, err
	case 12: // message.pod_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PodInfo)
		err := b.DecodeMessage(msg)
		m.Message = &Message_PodInfo{msg}
		return true, err
	case 13: // message.pod_data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PodData)
		err := b.DecodeMessage(msg)
		m.Message = &Message_PodData{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// message
	switch x := m.Message.(type) {
	case *Message_DeviceInfo:
		s := proto.Size(x.DeviceInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PodInfo:
		s := proto.Size(x.PodInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PodData:
		s := proto.Size(x.PodData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Cmd struct {
	SessionId uint64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Cmd:
	//	*Cmd_PodCmd
	Cmd                  isCmd_Cmd `protobuf_oneof:"cmd"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Cmd) Reset()         { *m = Cmd{} }
func (m *Cmd) String() string { return proto.CompactTextString(m) }
func (*Cmd) ProtoMessage()    {}
func (*Cmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_connectivity_d587803b39197f99, []int{1}
}
func (m *Cmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmd.Unmarshal(m, b)
}
func (m *Cmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmd.Marshal(b, m, deterministic)
}
func (dst *Cmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmd.Merge(dst, src)
}
func (m *Cmd) XXX_Size() int {
	return xxx_messageInfo_Cmd.Size(m)
}
func (m *Cmd) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmd.DiscardUnknown(m)
}

var xxx_messageInfo_Cmd proto.InternalMessageInfo

func (m *Cmd) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type isCmd_Cmd interface {
	isCmd_Cmd()
}

type Cmd_PodCmd struct {
	PodCmd *PodCmd `protobuf:"bytes,11,opt,name=pod_cmd,json=podCmd,proto3,oneof"`
}

func (*Cmd_PodCmd) isCmd_Cmd() {}

func (m *Cmd) GetCmd() isCmd_Cmd {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (m *Cmd) GetPodCmd() *PodCmd {
	if x, ok := m.GetCmd().(*Cmd_PodCmd); ok {
		return x.PodCmd
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Cmd) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Cmd_OneofMarshaler, _Cmd_OneofUnmarshaler, _Cmd_OneofSizer, []interface{}{
		(*Cmd_PodCmd)(nil),
	}
}

func _Cmd_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Cmd)
	// cmd
	switch x := m.Cmd.(type) {
	case *Cmd_PodCmd:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PodCmd); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Cmd.Cmd has unexpected type %T", x)
	}
	return nil
}

func _Cmd_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Cmd)
	switch tag {
	case 11: // cmd.pod_cmd
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PodCmd)
		err := b.DecodeMessage(msg)
		m.Cmd = &Cmd_PodCmd{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Cmd_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Cmd)
	// cmd
	switch x := m.Cmd.(type) {
	case *Cmd_PodCmd:
		s := proto.Size(x.PodCmd)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Message)(nil), "service.Message")
	proto.RegisterType((*Cmd)(nil), "service.Cmd")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnectivityClient is the client API for Connectivity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectivityClient interface {
	Sync(ctx context.Context, opts ...grpc.CallOption) (Connectivity_SyncClient, error)
}

type connectivityClient struct {
	cc *grpc.ClientConn
}

func NewConnectivityClient(cc *grpc.ClientConn) ConnectivityClient {
	return &connectivityClient{cc}
}

func (c *connectivityClient) Sync(ctx context.Context, opts ...grpc.CallOption) (Connectivity_SyncClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Connectivity_serviceDesc.Streams[0], "/service.Connectivity/Sync", opts...)
	if err != nil {
		return nil, err
	}
	x := &connectivitySyncClient{stream}
	return x, nil
}

type Connectivity_SyncClient interface {
	Send(*Message) error
	Recv() (*Cmd, error)
	grpc.ClientStream
}

type connectivitySyncClient struct {
	grpc.ClientStream
}

func (x *connectivitySyncClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *connectivitySyncClient) Recv() (*Cmd, error) {
	m := new(Cmd)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConnectivityServer is the server API for Connectivity service.
type ConnectivityServer interface {
	Sync(Connectivity_SyncServer) error
}

func RegisterConnectivityServer(s *grpc.Server, srv ConnectivityServer) {
	s.RegisterService(&_Connectivity_serviceDesc, srv)
}

func _Connectivity_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConnectivityServer).Sync(&connectivitySyncServer{stream})
}

type Connectivity_SyncServer interface {
	Send(*Cmd) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type connectivitySyncServer struct {
	grpc.ServerStream
}

func (x *connectivitySyncServer) Send(m *Cmd) error {
	return x.ServerStream.SendMsg(m)
}

func (x *connectivitySyncServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Connectivity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Connectivity",
	HandlerType: (*ConnectivityServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _Connectivity_Sync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "connectivity.proto",
}

func init() { proto.RegisterFile("connectivity.proto", fileDescriptor_connectivity_d587803b39197f99) }

var fileDescriptor_connectivity_d587803b39197f99 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xbb, 0xb6, 0x36, 0xcd, 0x34, 0xa2, 0xac, 0x97, 0x50, 0x14, 0x4a, 0x4f, 0xa1, 0x60,
	0x91, 0x0a, 0x1e, 0x3c, 0x36, 0x3d, 0xb4, 0x07, 0x21, 0xc4, 0x83, 0xc7, 0x10, 0x77, 0xb6, 0xb2,
	0xe0, 0xfe, 0xa1, 0xbb, 0x14, 0xfa, 0x89, 0xfd, 0x1a, 0x92, 0xec, 0x9a, 0x16, 0x3c, 0x78, 0x9b,
	0x79, 0xfb, 0x7e, 0xc3, 0xbc, 0x59, 0xa0, 0x4c, 0x2b, 0xc5, 0x99, 0x13, 0x07, 0xe1, 0x8e, 0x0b,
	0xb3, 0xd7, 0x4e, 0xd3, 0xc8, 0xf2, 0xfd, 0x41, 0x30, 0x3e, 0x89, 0x8d, 0x46, 0xaf, 0x4d, 0x12,
	0xe4, 0x8d, 0xe4, 0xbb, 0xd9, 0x37, 0x81, 0xe8, 0x95, 0x5b, 0x5b, 0x7f, 0x72, 0x7a, 0x0f, 0x60,
	0xb9, 0xb5, 0x42, 0xab, 0x4a, 0x60, 0x4a, 0xa6, 0x24, 0x1b, 0x94, 0x71, 0x50, 0xb6, 0x48, 0xef,
	0x20, 0x66, 0x5a, 0x9a, 0x2f, 0xee, 0x38, 0xa6, 0x17, 0x53, 0x92, 0x8d, 0xca, 0x93, 0x40, 0x9f,
	0x61, 0xec, 0x07, 0x57, 0x42, 0xed, 0x74, 0x3a, 0x9e, 0x92, 0x6c, 0xbc, 0xbc, 0x5d, 0x84, 0x05,
	0x16, 0xeb, 0xf6, 0x6d, 0xab, 0x76, 0x7a, 0xd3, 0x2b, 0x01, 0xbb, 0x8e, 0x3e, 0xc0, 0xc8, 0x68,
	0xf4, 0x50, 0xd2, 0x42, 0x37, 0x1d, 0x54, 0x68, 0x0c, 0x44, 0x64, 0x7c, 0xf9, 0x6b, 0xc7, 0xda,
	0xd5, 0xe9, 0xd5, 0x5f, 0xfb, 0xba, 0x76, 0x75, 0xb0, 0x37, 0xe5, 0x2a, 0x86, 0x48, 0xfa, 0x74,
	0xb3, 0x77, 0xe8, 0xe7, 0x12, 0xff, 0x0b, 0x39, 0x87, 0x86, 0xad, 0x98, 0xc4, 0x10, 0xe1, 0xfa,
	0x7c, 0x7c, 0x2e, 0x71, 0xd3, 0x2b, 0x87, 0xa6, 0xad, 0x56, 0x97, 0xd0, 0x67, 0x12, 0x97, 0x2f,
	0x90, 0xe4, 0x67, 0xa7, 0xa7, 0x73, 0x18, 0xbc, 0x1d, 0x15, 0xa3, 0xa7, 0xc5, 0xc2, 0x81, 0x27,
	0x49, 0xa7, 0xe4, 0x12, 0x33, 0xf2, 0x48, 0x8a, 0x5e, 0x41, 0x3e, 0x86, 0xed, 0x4f, 0x3c, 0xfd,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x55, 0x8d, 0xea, 0xaf, 0xc1, 0x01, 0x00, 0x00,
}
