// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device.proto

package connectivity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceInfo struct {
	// protobuf bytes of NodeSpec
	Spec []byte `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	// protobuf bytes of NodeStatus
	Status               []byte   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceInfo) Reset()         { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()    {}
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_199685a7ec539b14, []int{0}
}
func (m *DeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceInfo.Unmarshal(m, b)
}
func (m *DeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceInfo.Marshal(b, m, deterministic)
}
func (dst *DeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfo.Merge(dst, src)
}
func (m *DeviceInfo) XXX_Size() int {
	return xxx_messageInfo_DeviceInfo.Size(m)
}
func (m *DeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfo proto.InternalMessageInfo

func (m *DeviceInfo) GetSpec() []byte {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *DeviceInfo) GetStatus() []byte {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*DeviceInfo)(nil), "connectivity.DeviceInfo")
}

func init() { proto.RegisterFile("device.proto", fileDescriptor_device_199685a7ec539b14) }

var fileDescriptor_device_199685a7ec539b14 = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x49, 0x2d, 0xcb,
	0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x49, 0xce, 0xcf, 0xcb, 0x4b, 0x4d,
	0x2e, 0xc9, 0x2c, 0xcb, 0x2c, 0xa9, 0x54, 0xb2, 0xe0, 0xe2, 0x72, 0x01, 0xcb, 0x7a, 0xe6, 0xa5,
	0xe5, 0x0b, 0x09, 0x71, 0xb1, 0x14, 0x17, 0xa4, 0x26, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04,
	0x81, 0xd9, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x12, 0x4c, 0x60, 0x51,
	0x28, 0x2f, 0x89, 0x0d, 0x6c, 0x9c, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xff, 0xe2, 0xa1, 0xab,
	0x5e, 0x00, 0x00, 0x00,
}
