// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pod.proto

package connectivity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PodCmd_Action int32

const (
	PodCmd_CreateOrUpdate PodCmd_Action = 0
	PodCmd_Delete         PodCmd_Action = 1
	PodCmd_List           PodCmd_Action = 2
	PodCmd_Exec           PodCmd_Action = 3
	PodCmd_Attach         PodCmd_Action = 4
	PodCmd_Log            PodCmd_Action = 5
	PodCmd_PortForward    PodCmd_Action = 6
	PodCmd_Input          PodCmd_Action = 7
	PodCmd_ResizeTty      PodCmd_Action = 8
)

var PodCmd_Action_name = map[int32]string{
	0: "CreateOrUpdate",
	1: "Delete",
	2: "List",
	3: "Exec",
	4: "Attach",
	5: "Log",
	6: "PortForward",
	7: "Input",
	8: "ResizeTty",
}
var PodCmd_Action_value = map[string]int32{
	"CreateOrUpdate": 0,
	"Delete":         1,
	"List":           2,
	"Exec":           3,
	"Attach":         4,
	"Log":            5,
	"PortForward":    6,
	"Input":          7,
	"ResizeTty":      8,
}

func (x PodCmd_Action) String() string {
	return proto.EnumName(PodCmd_Action_name, int32(x))
}
func (PodCmd_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pod_6cd31e41f86edfd4, []int{1, 0}
}

type PodInfo struct {
	// Types that are valid to be assigned to Pod:
	//	*PodInfo_PodV1
	Pod                  isPodInfo_Pod `protobuf_oneof:"pod"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PodInfo) Reset()         { *m = PodInfo{} }
func (m *PodInfo) String() string { return proto.CompactTextString(m) }
func (*PodInfo) ProtoMessage()    {}
func (*PodInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_6cd31e41f86edfd4, []int{0}
}
func (m *PodInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodInfo.Unmarshal(m, b)
}
func (m *PodInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodInfo.Marshal(b, m, deterministic)
}
func (dst *PodInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodInfo.Merge(dst, src)
}
func (m *PodInfo) XXX_Size() int {
	return xxx_messageInfo_PodInfo.Size(m)
}
func (m *PodInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PodInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PodInfo proto.InternalMessageInfo

type isPodInfo_Pod interface {
	isPodInfo_Pod()
}

type PodInfo_PodV1 struct {
	PodV1 []byte `protobuf:"bytes,1,opt,name=pod_v1,json=podV1,proto3,oneof"`
}

func (*PodInfo_PodV1) isPodInfo_Pod() {}

func (m *PodInfo) GetPod() isPodInfo_Pod {
	if m != nil {
		return m.Pod
	}
	return nil
}

func (m *PodInfo) GetPodV1() []byte {
	if x, ok := m.GetPod().(*PodInfo_PodV1); ok {
		return x.PodV1
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PodInfo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PodInfo_OneofMarshaler, _PodInfo_OneofUnmarshaler, _PodInfo_OneofSizer, []interface{}{
		(*PodInfo_PodV1)(nil),
	}
}

func _PodInfo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PodInfo)
	// pod
	switch x := m.Pod.(type) {
	case *PodInfo_PodV1:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.PodV1)
	case nil:
	default:
		return fmt.Errorf("PodInfo.Pod has unexpected type %T", x)
	}
	return nil
}

func _PodInfo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PodInfo)
	switch tag {
	case 1: // pod.pod_v1
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Pod = &PodInfo_PodV1{x}
		return true, err
	default:
		return false, nil
	}
}

func _PodInfo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PodInfo)
	// pod
	switch x := m.Pod.(type) {
	case *PodInfo_PodV1:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.PodV1)))
		n += len(x.PodV1)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PodCmd struct {
	// pod namespace
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// pod name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// action type
	Action PodCmd_Action `protobuf:"varint,3,opt,name=action,proto3,enum=connectivity.PodCmd_Action" json:"action,omitempty"`
	// options for action
	//
	// Types that are valid to be assigned to Options:
	//	*PodCmd_CreateOptions
	//	*PodCmd_DeleteOptions
	//	*PodCmd_ListOptions
	//	*PodCmd_LogOptions
	//	*PodCmd_ExecOptions
	//	*PodCmd_PortForwardOptions
	//	*PodCmd_InputOptions
	//	*PodCmd_ResizeOptions
	Options              isPodCmd_Options `protobuf_oneof:"options"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PodCmd) Reset()         { *m = PodCmd{} }
func (m *PodCmd) String() string { return proto.CompactTextString(m) }
func (*PodCmd) ProtoMessage()    {}
func (*PodCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_6cd31e41f86edfd4, []int{1}
}
func (m *PodCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodCmd.Unmarshal(m, b)
}
func (m *PodCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodCmd.Marshal(b, m, deterministic)
}
func (dst *PodCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodCmd.Merge(dst, src)
}
func (m *PodCmd) XXX_Size() int {
	return xxx_messageInfo_PodCmd.Size(m)
}
func (m *PodCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_PodCmd.DiscardUnknown(m)
}

var xxx_messageInfo_PodCmd proto.InternalMessageInfo

func (m *PodCmd) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PodCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PodCmd) GetAction() PodCmd_Action {
	if m != nil {
		return m.Action
	}
	return PodCmd_CreateOrUpdate
}

type isPodCmd_Options interface {
	isPodCmd_Options()
}

type PodCmd_CreateOptions struct {
	CreateOptions *CreateOptions `protobuf:"bytes,11,opt,name=create_options,json=createOptions,proto3,oneof"`
}

type PodCmd_DeleteOptions struct {
	DeleteOptions *DeleteOptions `protobuf:"bytes,12,opt,name=delete_options,json=deleteOptions,proto3,oneof"`
}

type PodCmd_ListOptions struct {
	ListOptions *ListOptions `protobuf:"bytes,13,opt,name=list_options,json=listOptions,proto3,oneof"`
}

type PodCmd_LogOptions struct {
	LogOptions *LogOptions `protobuf:"bytes,14,opt,name=log_options,json=logOptions,proto3,oneof"`
}

type PodCmd_ExecOptions struct {
	ExecOptions *ExecOptions `protobuf:"bytes,15,opt,name=exec_options,json=execOptions,proto3,oneof"`
}

type PodCmd_PortForwardOptions struct {
	PortForwardOptions *PortForwardOptions `protobuf:"bytes,16,opt,name=port_forward_options,json=portForwardOptions,proto3,oneof"`
}

type PodCmd_InputOptions struct {
	InputOptions *InputOptions `protobuf:"bytes,17,opt,name=input_options,json=inputOptions,proto3,oneof"`
}

type PodCmd_ResizeOptions struct {
	ResizeOptions *TtyResizeOptions `protobuf:"bytes,18,opt,name=resize_options,json=resizeOptions,proto3,oneof"`
}

func (*PodCmd_CreateOptions) isPodCmd_Options() {}

func (*PodCmd_DeleteOptions) isPodCmd_Options() {}

func (*PodCmd_ListOptions) isPodCmd_Options() {}

func (*PodCmd_LogOptions) isPodCmd_Options() {}

func (*PodCmd_ExecOptions) isPodCmd_Options() {}

func (*PodCmd_PortForwardOptions) isPodCmd_Options() {}

func (*PodCmd_InputOptions) isPodCmd_Options() {}

func (*PodCmd_ResizeOptions) isPodCmd_Options() {}

func (m *PodCmd) GetOptions() isPodCmd_Options {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *PodCmd) GetCreateOptions() *CreateOptions {
	if x, ok := m.GetOptions().(*PodCmd_CreateOptions); ok {
		return x.CreateOptions
	}
	return nil
}

func (m *PodCmd) GetDeleteOptions() *DeleteOptions {
	if x, ok := m.GetOptions().(*PodCmd_DeleteOptions); ok {
		return x.DeleteOptions
	}
	return nil
}

func (m *PodCmd) GetListOptions() *ListOptions {
	if x, ok := m.GetOptions().(*PodCmd_ListOptions); ok {
		return x.ListOptions
	}
	return nil
}

func (m *PodCmd) GetLogOptions() *LogOptions {
	if x, ok := m.GetOptions().(*PodCmd_LogOptions); ok {
		return x.LogOptions
	}
	return nil
}

func (m *PodCmd) GetExecOptions() *ExecOptions {
	if x, ok := m.GetOptions().(*PodCmd_ExecOptions); ok {
		return x.ExecOptions
	}
	return nil
}

func (m *PodCmd) GetPortForwardOptions() *PortForwardOptions {
	if x, ok := m.GetOptions().(*PodCmd_PortForwardOptions); ok {
		return x.PortForwardOptions
	}
	return nil
}

func (m *PodCmd) GetInputOptions() *InputOptions {
	if x, ok := m.GetOptions().(*PodCmd_InputOptions); ok {
		return x.InputOptions
	}
	return nil
}

func (m *PodCmd) GetResizeOptions() *TtyResizeOptions {
	if x, ok := m.GetOptions().(*PodCmd_ResizeOptions); ok {
		return x.ResizeOptions
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PodCmd) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PodCmd_OneofMarshaler, _PodCmd_OneofUnmarshaler, _PodCmd_OneofSizer, []interface{}{
		(*PodCmd_CreateOptions)(nil),
		(*PodCmd_DeleteOptions)(nil),
		(*PodCmd_ListOptions)(nil),
		(*PodCmd_LogOptions)(nil),
		(*PodCmd_ExecOptions)(nil),
		(*PodCmd_PortForwardOptions)(nil),
		(*PodCmd_InputOptions)(nil),
		(*PodCmd_ResizeOptions)(nil),
	}
}

func _PodCmd_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PodCmd)
	// options
	switch x := m.Options.(type) {
	case *PodCmd_CreateOptions:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateOptions); err != nil {
			return err
		}
	case *PodCmd_DeleteOptions:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeleteOptions); err != nil {
			return err
		}
	case *PodCmd_ListOptions:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ListOptions); err != nil {
			return err
		}
	case *PodCmd_LogOptions:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LogOptions); err != nil {
			return err
		}
	case *PodCmd_ExecOptions:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExecOptions); err != nil {
			return err
		}
	case *PodCmd_PortForwardOptions:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PortForwardOptions); err != nil {
			return err
		}
	case *PodCmd_InputOptions:
		b.EncodeVarint(17<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InputOptions); err != nil {
			return err
		}
	case *PodCmd_ResizeOptions:
		b.EncodeVarint(18<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ResizeOptions); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PodCmd.Options has unexpected type %T", x)
	}
	return nil
}

func _PodCmd_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PodCmd)
	switch tag {
	case 11: // options.create_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateOptions)
		err := b.DecodeMessage(msg)
		m.Options = &PodCmd_CreateOptions{msg}
		return true, err
	case 12: // options.delete_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeleteOptions)
		err := b.DecodeMessage(msg)
		m.Options = &PodCmd_DeleteOptions{msg}
		return true, err
	case 13: // options.list_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ListOptions)
		err := b.DecodeMessage(msg)
		m.Options = &PodCmd_ListOptions{msg}
		return true, err
	case 14: // options.log_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LogOptions)
		err := b.DecodeMessage(msg)
		m.Options = &PodCmd_LogOptions{msg}
		return true, err
	case 15: // options.exec_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExecOptions)
		err := b.DecodeMessage(msg)
		m.Options = &PodCmd_ExecOptions{msg}
		return true, err
	case 16: // options.port_forward_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PortForwardOptions)
		err := b.DecodeMessage(msg)
		m.Options = &PodCmd_PortForwardOptions{msg}
		return true, err
	case 17: // options.input_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InputOptions)
		err := b.DecodeMessage(msg)
		m.Options = &PodCmd_InputOptions{msg}
		return true, err
	case 18: // options.resize_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TtyResizeOptions)
		err := b.DecodeMessage(msg)
		m.Options = &PodCmd_ResizeOptions{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PodCmd_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PodCmd)
	// options
	switch x := m.Options.(type) {
	case *PodCmd_CreateOptions:
		s := proto.Size(x.CreateOptions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_DeleteOptions:
		s := proto.Size(x.DeleteOptions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_ListOptions:
		s := proto.Size(x.ListOptions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_LogOptions:
		s := proto.Size(x.LogOptions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_ExecOptions:
		s := proto.Size(x.ExecOptions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_PortForwardOptions:
		s := proto.Size(x.PortForwardOptions)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_InputOptions:
		s := proto.Size(x.InputOptions)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_ResizeOptions:
		s := proto.Size(x.ResizeOptions)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateOptions struct {
	// Types that are valid to be assigned to Pod:
	//	*CreateOptions_PodV1
	Pod                  isCreateOptions_Pod `protobuf_oneof:"pod"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateOptions) Reset()         { *m = CreateOptions{} }
func (m *CreateOptions) String() string { return proto.CompactTextString(m) }
func (*CreateOptions) ProtoMessage()    {}
func (*CreateOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_6cd31e41f86edfd4, []int{2}
}
func (m *CreateOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOptions.Unmarshal(m, b)
}
func (m *CreateOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOptions.Marshal(b, m, deterministic)
}
func (dst *CreateOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOptions.Merge(dst, src)
}
func (m *CreateOptions) XXX_Size() int {
	return xxx_messageInfo_CreateOptions.Size(m)
}
func (m *CreateOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOptions.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOptions proto.InternalMessageInfo

type isCreateOptions_Pod interface {
	isCreateOptions_Pod()
}

type CreateOptions_PodV1 struct {
	PodV1 *PodV1 `protobuf:"bytes,1,opt,name=pod_v1,json=podV1,proto3,oneof"`
}

func (*CreateOptions_PodV1) isCreateOptions_Pod() {}

func (m *CreateOptions) GetPod() isCreateOptions_Pod {
	if m != nil {
		return m.Pod
	}
	return nil
}

func (m *CreateOptions) GetPodV1() *PodV1 {
	if x, ok := m.GetPod().(*CreateOptions_PodV1); ok {
		return x.PodV1
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CreateOptions) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CreateOptions_OneofMarshaler, _CreateOptions_OneofUnmarshaler, _CreateOptions_OneofSizer, []interface{}{
		(*CreateOptions_PodV1)(nil),
	}
}

func _CreateOptions_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CreateOptions)
	// pod
	switch x := m.Pod.(type) {
	case *CreateOptions_PodV1:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PodV1); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CreateOptions.Pod has unexpected type %T", x)
	}
	return nil
}

func _CreateOptions_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CreateOptions)
	switch tag {
	case 1: // pod.pod_v1
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PodV1)
		err := b.DecodeMessage(msg)
		m.Pod = &CreateOptions_PodV1{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CreateOptions_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CreateOptions)
	// pod
	switch x := m.Pod.(type) {
	case *CreateOptions_PodV1:
		s := proto.Size(x.PodV1)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PodV1 struct {
	Pod                  []byte   `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	PullSecret           [][]byte `protobuf:"bytes,2,rep,name=pull_secret,json=pullSecret,proto3" json:"pull_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodV1) Reset()         { *m = PodV1{} }
func (m *PodV1) String() string { return proto.CompactTextString(m) }
func (*PodV1) ProtoMessage()    {}
func (*PodV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_6cd31e41f86edfd4, []int{3}
}
func (m *PodV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodV1.Unmarshal(m, b)
}
func (m *PodV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodV1.Marshal(b, m, deterministic)
}
func (dst *PodV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodV1.Merge(dst, src)
}
func (m *PodV1) XXX_Size() int {
	return xxx_messageInfo_PodV1.Size(m)
}
func (m *PodV1) XXX_DiscardUnknown() {
	xxx_messageInfo_PodV1.DiscardUnknown(m)
}

var xxx_messageInfo_PodV1 proto.InternalMessageInfo

func (m *PodV1) GetPod() []byte {
	if m != nil {
		return m.Pod
	}
	return nil
}

func (m *PodV1) GetPullSecret() [][]byte {
	if m != nil {
		return m.PullSecret
	}
	return nil
}

type DeleteOptions struct {
	GraceTime            int64    `protobuf:"varint,1,opt,name=grace_time,json=graceTime,proto3" json:"grace_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOptions) Reset()         { *m = DeleteOptions{} }
func (m *DeleteOptions) String() string { return proto.CompactTextString(m) }
func (*DeleteOptions) ProtoMessage()    {}
func (*DeleteOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_6cd31e41f86edfd4, []int{4}
}
func (m *DeleteOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOptions.Unmarshal(m, b)
}
func (m *DeleteOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOptions.Marshal(b, m, deterministic)
}
func (dst *DeleteOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOptions.Merge(dst, src)
}
func (m *DeleteOptions) XXX_Size() int {
	return xxx_messageInfo_DeleteOptions.Size(m)
}
func (m *DeleteOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOptions.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOptions proto.InternalMessageInfo

func (m *DeleteOptions) GetGraceTime() int64 {
	if m != nil {
		return m.GraceTime
	}
	return 0
}

type ListOptions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOptions) Reset()         { *m = ListOptions{} }
func (m *ListOptions) String() string { return proto.CompactTextString(m) }
func (*ListOptions) ProtoMessage()    {}
func (*ListOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_6cd31e41f86edfd4, []int{5}
}
func (m *ListOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOptions.Unmarshal(m, b)
}
func (m *ListOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOptions.Marshal(b, m, deterministic)
}
func (dst *ListOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOptions.Merge(dst, src)
}
func (m *ListOptions) XXX_Size() int {
	return xxx_messageInfo_ListOptions.Size(m)
}
func (m *ListOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ListOptions proto.InternalMessageInfo

type LogOptions struct {
	// Types that are valid to be assigned to LogOptions:
	//	*LogOptions_LogOptionsV1
	LogOptions           isLogOptions_LogOptions `protobuf_oneof:"log_options"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LogOptions) Reset()         { *m = LogOptions{} }
func (m *LogOptions) String() string { return proto.CompactTextString(m) }
func (*LogOptions) ProtoMessage()    {}
func (*LogOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_6cd31e41f86edfd4, []int{6}
}
func (m *LogOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogOptions.Unmarshal(m, b)
}
func (m *LogOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogOptions.Marshal(b, m, deterministic)
}
func (dst *LogOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogOptions.Merge(dst, src)
}
func (m *LogOptions) XXX_Size() int {
	return xxx_messageInfo_LogOptions.Size(m)
}
func (m *LogOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_LogOptions.DiscardUnknown(m)
}

var xxx_messageInfo_LogOptions proto.InternalMessageInfo

type isLogOptions_LogOptions interface {
	isLogOptions_LogOptions()
}

type LogOptions_LogOptionsV1 struct {
	LogOptionsV1 []byte `protobuf:"bytes,1,opt,name=log_options_v1,json=logOptionsV1,proto3,oneof"`
}

func (*LogOptions_LogOptionsV1) isLogOptions_LogOptions() {}

func (m *LogOptions) GetLogOptions() isLogOptions_LogOptions {
	if m != nil {
		return m.LogOptions
	}
	return nil
}

func (m *LogOptions) GetLogOptionsV1() []byte {
	if x, ok := m.GetLogOptions().(*LogOptions_LogOptionsV1); ok {
		return x.LogOptionsV1
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*LogOptions) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _LogOptions_OneofMarshaler, _LogOptions_OneofUnmarshaler, _LogOptions_OneofSizer, []interface{}{
		(*LogOptions_LogOptionsV1)(nil),
	}
}

func _LogOptions_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*LogOptions)
	// log_options
	switch x := m.LogOptions.(type) {
	case *LogOptions_LogOptionsV1:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.LogOptionsV1)
	case nil:
	default:
		return fmt.Errorf("LogOptions.LogOptions has unexpected type %T", x)
	}
	return nil
}

func _LogOptions_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*LogOptions)
	switch tag {
	case 1: // log_options.log_options_v1
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.LogOptions = &LogOptions_LogOptionsV1{x}
		return true, err
	default:
		return false, nil
	}
}

func _LogOptions_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*LogOptions)
	// log_options
	switch x := m.LogOptions.(type) {
	case *LogOptions_LogOptionsV1:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.LogOptionsV1)))
		n += len(x.LogOptionsV1)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ExecOptions struct {
	// Types that are valid to be assigned to ExecOptions:
	//	*ExecOptions_ExecOptionsV1
	ExecOptions          isExecOptions_ExecOptions `protobuf_oneof:"exec_options"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ExecOptions) Reset()         { *m = ExecOptions{} }
func (m *ExecOptions) String() string { return proto.CompactTextString(m) }
func (*ExecOptions) ProtoMessage()    {}
func (*ExecOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_6cd31e41f86edfd4, []int{7}
}
func (m *ExecOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecOptions.Unmarshal(m, b)
}
func (m *ExecOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecOptions.Marshal(b, m, deterministic)
}
func (dst *ExecOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecOptions.Merge(dst, src)
}
func (m *ExecOptions) XXX_Size() int {
	return xxx_messageInfo_ExecOptions.Size(m)
}
func (m *ExecOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ExecOptions proto.InternalMessageInfo

type isExecOptions_ExecOptions interface {
	isExecOptions_ExecOptions()
}

type ExecOptions_ExecOptionsV1 struct {
	ExecOptionsV1 []byte `protobuf:"bytes,1,opt,name=exec_options_v1,json=execOptionsV1,proto3,oneof"`
}

func (*ExecOptions_ExecOptionsV1) isExecOptions_ExecOptions() {}

func (m *ExecOptions) GetExecOptions() isExecOptions_ExecOptions {
	if m != nil {
		return m.ExecOptions
	}
	return nil
}

func (m *ExecOptions) GetExecOptionsV1() []byte {
	if x, ok := m.GetExecOptions().(*ExecOptions_ExecOptionsV1); ok {
		return x.ExecOptionsV1
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ExecOptions) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ExecOptions_OneofMarshaler, _ExecOptions_OneofUnmarshaler, _ExecOptions_OneofSizer, []interface{}{
		(*ExecOptions_ExecOptionsV1)(nil),
	}
}

func _ExecOptions_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ExecOptions)
	// exec_options
	switch x := m.ExecOptions.(type) {
	case *ExecOptions_ExecOptionsV1:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.ExecOptionsV1)
	case nil:
	default:
		return fmt.Errorf("ExecOptions.ExecOptions has unexpected type %T", x)
	}
	return nil
}

func _ExecOptions_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ExecOptions)
	switch tag {
	case 1: // exec_options.exec_options_v1
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.ExecOptions = &ExecOptions_ExecOptionsV1{x}
		return true, err
	default:
		return false, nil
	}
}

func _ExecOptions_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ExecOptions)
	// exec_options
	switch x := m.ExecOptions.(type) {
	case *ExecOptions_ExecOptionsV1:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.ExecOptionsV1)))
		n += len(x.ExecOptionsV1)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PortForwardOptions struct {
	// Types that are valid to be assigned to PortForwardOptions:
	//	*PortForwardOptions_PortforwardOptionsV1
	PortForwardOptions   isPortForwardOptions_PortForwardOptions `protobuf_oneof:"port_forward_options"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *PortForwardOptions) Reset()         { *m = PortForwardOptions{} }
func (m *PortForwardOptions) String() string { return proto.CompactTextString(m) }
func (*PortForwardOptions) ProtoMessage()    {}
func (*PortForwardOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_6cd31e41f86edfd4, []int{8}
}
func (m *PortForwardOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortForwardOptions.Unmarshal(m, b)
}
func (m *PortForwardOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortForwardOptions.Marshal(b, m, deterministic)
}
func (dst *PortForwardOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortForwardOptions.Merge(dst, src)
}
func (m *PortForwardOptions) XXX_Size() int {
	return xxx_messageInfo_PortForwardOptions.Size(m)
}
func (m *PortForwardOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_PortForwardOptions.DiscardUnknown(m)
}

var xxx_messageInfo_PortForwardOptions proto.InternalMessageInfo

type isPortForwardOptions_PortForwardOptions interface {
	isPortForwardOptions_PortForwardOptions()
}

type PortForwardOptions_PortforwardOptionsV1 struct {
	PortforwardOptionsV1 []byte `protobuf:"bytes,1,opt,name=portforward_options_v1,json=portforwardOptionsV1,proto3,oneof"`
}

func (*PortForwardOptions_PortforwardOptionsV1) isPortForwardOptions_PortForwardOptions() {}

func (m *PortForwardOptions) GetPortForwardOptions() isPortForwardOptions_PortForwardOptions {
	if m != nil {
		return m.PortForwardOptions
	}
	return nil
}

func (m *PortForwardOptions) GetPortforwardOptionsV1() []byte {
	if x, ok := m.GetPortForwardOptions().(*PortForwardOptions_PortforwardOptionsV1); ok {
		return x.PortforwardOptionsV1
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PortForwardOptions) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PortForwardOptions_OneofMarshaler, _PortForwardOptions_OneofUnmarshaler, _PortForwardOptions_OneofSizer, []interface{}{
		(*PortForwardOptions_PortforwardOptionsV1)(nil),
	}
}

func _PortForwardOptions_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PortForwardOptions)
	// port_forward_options
	switch x := m.PortForwardOptions.(type) {
	case *PortForwardOptions_PortforwardOptionsV1:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.PortforwardOptionsV1)
	case nil:
	default:
		return fmt.Errorf("PortForwardOptions.PortForwardOptions has unexpected type %T", x)
	}
	return nil
}

func _PortForwardOptions_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PortForwardOptions)
	switch tag {
	case 1: // port_forward_options.portforward_options_v1
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.PortForwardOptions = &PortForwardOptions_PortforwardOptionsV1{x}
		return true, err
	default:
		return false, nil
	}
}

func _PortForwardOptions_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PortForwardOptions)
	// port_forward_options
	switch x := m.PortForwardOptions.(type) {
	case *PortForwardOptions_PortforwardOptionsV1:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.PortforwardOptionsV1)))
		n += len(x.PortforwardOptionsV1)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type InputOptions struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputOptions) Reset()         { *m = InputOptions{} }
func (m *InputOptions) String() string { return proto.CompactTextString(m) }
func (*InputOptions) ProtoMessage()    {}
func (*InputOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_6cd31e41f86edfd4, []int{9}
}
func (m *InputOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputOptions.Unmarshal(m, b)
}
func (m *InputOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputOptions.Marshal(b, m, deterministic)
}
func (dst *InputOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputOptions.Merge(dst, src)
}
func (m *InputOptions) XXX_Size() int {
	return xxx_messageInfo_InputOptions.Size(m)
}
func (m *InputOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_InputOptions.DiscardUnknown(m)
}

var xxx_messageInfo_InputOptions proto.InternalMessageInfo

func (m *InputOptions) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type TtyResizeOptions struct {
	Cols                 uint32   `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows                 uint32   `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TtyResizeOptions) Reset()         { *m = TtyResizeOptions{} }
func (m *TtyResizeOptions) String() string { return proto.CompactTextString(m) }
func (*TtyResizeOptions) ProtoMessage()    {}
func (*TtyResizeOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_6cd31e41f86edfd4, []int{10}
}
func (m *TtyResizeOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TtyResizeOptions.Unmarshal(m, b)
}
func (m *TtyResizeOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TtyResizeOptions.Marshal(b, m, deterministic)
}
func (dst *TtyResizeOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TtyResizeOptions.Merge(dst, src)
}
func (m *TtyResizeOptions) XXX_Size() int {
	return xxx_messageInfo_TtyResizeOptions.Size(m)
}
func (m *TtyResizeOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_TtyResizeOptions.DiscardUnknown(m)
}

var xxx_messageInfo_TtyResizeOptions proto.InternalMessageInfo

func (m *TtyResizeOptions) GetCols() uint32 {
	if m != nil {
		return m.Cols
	}
	return 0
}

func (m *TtyResizeOptions) GetRows() uint32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func init() {
	proto.RegisterType((*PodInfo)(nil), "connectivity.PodInfo")
	proto.RegisterType((*PodCmd)(nil), "connectivity.PodCmd")
	proto.RegisterType((*CreateOptions)(nil), "connectivity.CreateOptions")
	proto.RegisterType((*PodV1)(nil), "connectivity.PodV1")
	proto.RegisterType((*DeleteOptions)(nil), "connectivity.DeleteOptions")
	proto.RegisterType((*ListOptions)(nil), "connectivity.ListOptions")
	proto.RegisterType((*LogOptions)(nil), "connectivity.LogOptions")
	proto.RegisterType((*ExecOptions)(nil), "connectivity.ExecOptions")
	proto.RegisterType((*PortForwardOptions)(nil), "connectivity.PortForwardOptions")
	proto.RegisterType((*InputOptions)(nil), "connectivity.InputOptions")
	proto.RegisterType((*TtyResizeOptions)(nil), "connectivity.TtyResizeOptions")
	proto.RegisterEnum("connectivity.PodCmd_Action", PodCmd_Action_name, PodCmd_Action_value)
}

func init() { proto.RegisterFile("pod.proto", fileDescriptor_pod_6cd31e41f86edfd4) }

var fileDescriptor_pod_6cd31e41f86edfd4 = []byte{
	// 633 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0x5d, 0x6b, 0xdb, 0x3c,
	0x14, 0xc7, 0x9b, 0xa6, 0x71, 0xea, 0xe3, 0x97, 0xfa, 0x39, 0x4f, 0xe9, 0xb2, 0xf7, 0xe0, 0x8b,
	0x91, 0xc1, 0x08, 0xa4, 0x85, 0x5d, 0x74, 0x30, 0x68, 0xda, 0xad, 0x2d, 0x14, 0x56, 0xbc, 0x2c,
	0xb7, 0xc1, 0xb3, 0xd4, 0xcc, 0xe0, 0x58, 0x42, 0x56, 0xdf, 0xc6, 0xbe, 0xcd, 0xbe, 0xe8, 0x90,
	0x1c, 0x22, 0x39, 0xe9, 0xdd, 0x39, 0x47, 0xff, 0xf3, 0xb3, 0x2c, 0xfd, 0x8f, 0xc0, 0xe5, 0x8c,
	0x0c, 0xb9, 0x60, 0x92, 0xa1, 0x9f, 0xb1, 0xb2, 0xa4, 0x99, 0xcc, 0xef, 0x72, 0xf9, 0x18, 0xbf,
	0x87, 0xee, 0x35, 0x23, 0x97, 0xe5, 0x0d, 0xc3, 0x67, 0xe0, 0x70, 0x46, 0x66, 0x77, 0xa3, 0x5e,
	0xab, 0xdf, 0x1a, 0xf8, 0x17, 0x5b, 0x49, 0x87, 0x33, 0x32, 0x1d, 0x8d, 0x3b, 0xd0, 0xe6, 0x8c,
	0xc4, 0x7f, 0x1d, 0x70, 0xae, 0x19, 0x39, 0x5d, 0x10, 0x7c, 0x05, 0x6e, 0x99, 0x2e, 0x68, 0xc5,
	0xd3, 0x8c, 0x6a, 0xb5, 0x9b, 0x98, 0x02, 0x22, 0xec, 0xa8, 0xa4, 0xb7, 0xad, 0x17, 0x74, 0x8c,
	0x47, 0xe0, 0xa4, 0x99, 0xcc, 0x59, 0xd9, 0x6b, 0xf7, 0x5b, 0x83, 0xf0, 0xf0, 0xe5, 0xd0, 0xde,
	0xc6, 0xb0, 0xe6, 0x0e, 0x4f, 0xb4, 0x24, 0x59, 0x4a, 0xf1, 0x0c, 0xc2, 0x4c, 0xd0, 0x54, 0xd2,
	0x19, 0xe3, 0xaa, 0x50, 0xf5, 0xbc, 0x7e, 0x6b, 0xe0, 0xad, 0x37, 0x9f, 0x6a, 0xcd, 0xb7, 0x5a,
	0x72, 0xb1, 0x95, 0x04, 0x99, 0x5d, 0x50, 0x14, 0x42, 0x0b, 0x6a, 0x51, 0xfc, 0xa7, 0x28, 0x67,
	0x5a, 0x63, 0x51, 0x88, 0x5d, 0xc0, 0xcf, 0xe0, 0x17, 0x79, 0x25, 0x57, 0x8c, 0x40, 0x33, 0x9e,
	0x37, 0x19, 0x57, 0x79, 0x25, 0x0d, 0xc1, 0x2b, 0x4c, 0x8a, 0x9f, 0xc0, 0x2b, 0xd8, 0x7c, 0xd5,
	0x1e, 0xea, 0xf6, 0xde, 0x5a, 0x3b, 0x9b, 0x9b, 0x6e, 0x28, 0x56, 0x99, 0xfa, 0x38, 0x7d, 0xa0,
	0xd9, 0xaa, 0x7b, 0xef, 0xa9, 0x8f, 0x7f, 0x79, 0xa0, 0x99, 0xf5, 0x71, 0x6a, 0x52, 0x9c, 0xc0,
	0x3e, 0x67, 0x42, 0xce, 0x6e, 0x98, 0xb8, 0x4f, 0x05, 0x59, 0x71, 0x22, 0xcd, 0xe9, 0xaf, 0xdf,
	0x85, 0x90, 0x5f, 0x6b, 0xa1, 0xc1, 0x21, 0xdf, 0xa8, 0xe2, 0x09, 0x04, 0x79, 0xc9, 0x6f, 0xcd,
	0x99, 0xfc, 0xa7, 0x71, 0x2f, 0x9a, 0xb8, 0x4b, 0x25, 0x31, 0x20, 0x3f, 0xb7, 0x72, 0x3c, 0x87,
	0x50, 0xd0, 0x2a, 0xff, 0x6d, 0xee, 0x06, 0x35, 0xe3, 0x4d, 0x93, 0x31, 0x91, 0x8f, 0x89, 0x96,
	0x59, 0xd7, 0x23, 0xec, 0x42, 0xfc, 0x07, 0x9c, 0xda, 0x3c, 0x88, 0x10, 0x2e, 0x0d, 0x21, 0x7e,
	0x70, 0x92, 0x4a, 0x1a, 0x6d, 0x21, 0x80, 0x53, 0x5f, 0x6f, 0xd4, 0xc2, 0x5d, 0xd8, 0x51, 0xd7,
	0x14, 0x6d, 0xab, 0x48, 0x9d, 0x59, 0xd4, 0x56, 0xeb, 0x27, 0x52, 0xa6, 0xd9, 0xaf, 0x68, 0x07,
	0xbb, 0xd0, 0xbe, 0x62, 0xf3, 0xa8, 0x83, 0x7b, 0xe0, 0x59, 0x47, 0x11, 0x39, 0xe8, 0x42, 0x47,
	0xff, 0x4c, 0xd4, 0xc5, 0x00, 0xdc, 0x7a, 0x43, 0x13, 0xf9, 0x18, 0xed, 0x8e, 0x5d, 0xe8, 0x2e,
	0xf7, 0x1f, 0x9f, 0x41, 0xd0, 0xf0, 0x23, 0x7e, 0x68, 0x8c, 0x95, 0x77, 0xf8, 0xff, 0x86, 0xf3,
	0xa7, 0xa3, 0x8d, 0x59, 0x3b, 0x86, 0x8e, 0x5e, 0xc0, 0x48, 0xe7, 0xf5, 0x44, 0x26, 0x2a, 0xc4,
	0xb7, 0xe0, 0xf1, 0xdb, 0xa2, 0x98, 0x55, 0x34, 0x13, 0x54, 0xf6, 0xb6, 0xfb, 0xed, 0x81, 0x9f,
	0x80, 0x2a, 0x7d, 0xd7, 0x95, 0x78, 0x08, 0x41, 0xc3, 0xcb, 0xf8, 0x1a, 0x60, 0x2e, 0xd2, 0x8c,
	0xce, 0x64, 0xbe, 0xa8, 0xc7, 0xb5, 0x9d, 0xb8, 0xba, 0x32, 0xc9, 0x17, 0x34, 0x0e, 0xc0, 0xb3,
	0x7c, 0x1b, 0x9f, 0x02, 0x18, 0x1f, 0xe2, 0x3b, 0x08, 0x2d, 0xdb, 0xda, 0x8f, 0x83, 0x6f, 0xfc,
	0x39, 0x1d, 0x8d, 0x83, 0x86, 0xbd, 0xe3, 0x73, 0xf0, 0x2c, 0x3b, 0xe2, 0x00, 0xf6, 0x6c, 0xff,
	0xda, 0x98, 0xc0, 0xf2, 0xe9, 0x74, 0x34, 0x0e, 0x9b, 0x4e, 0x8f, 0x09, 0xe0, 0xa6, 0x1f, 0xf1,
	0x23, 0x1c, 0x28, 0x3f, 0xae, 0xd9, 0xd9, 0xc6, 0xee, 0x5b, 0xeb, 0x86, 0x7e, 0xf0, 0xf4, 0x1c,
	0xc4, 0x31, 0xf8, 0xb6, 0x4d, 0xd5, 0x0b, 0x46, 0x52, 0x99, 0x2e, 0x8f, 0x5d, 0xc7, 0xf1, 0x31,
	0x44, 0xeb, 0x36, 0x54, 0xba, 0x8c, 0x15, 0x95, 0xd6, 0x05, 0x89, 0x8e, 0x55, 0x4d, 0xb0, 0xfb,
	0x4a, 0xbf, 0x7e, 0x41, 0xa2, 0xe3, 0x9f, 0x8e, 0x7e, 0x7a, 0x8f, 0xfe, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x2f, 0x68, 0xb7, 0x46, 0x87, 0x05, 0x00, 0x00,
}
