// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pod.proto

package connectivity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PodInfo_Phase int32

const (
	PodInfo_Created PodInfo_Phase = 0
	PodInfo_Running PodInfo_Phase = 1
	PodInfo_Deleted PodInfo_Phase = 2
	PodInfo_Updated PodInfo_Phase = 3
)

var PodInfo_Phase_name = map[int32]string{
	0: "Created",
	1: "Running",
	2: "Deleted",
	3: "Updated",
}
var PodInfo_Phase_value = map[string]int32{
	"Created": 0,
	"Running": 1,
	"Deleted": 2,
	"Updated": 3,
}

func (x PodInfo_Phase) String() string {
	return proto.EnumName(PodInfo_Phase_name, int32(x))
}
func (PodInfo_Phase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pod_b7467315d22ba53a, []int{0, 0}
}

type PodCmd_ActionType int32

const (
	PodCmd_CreateOrUpdate PodCmd_ActionType = 0
	PodCmd_Delete         PodCmd_ActionType = 1
	PodCmd_List           PodCmd_ActionType = 2
	PodCmd_Exec           PodCmd_ActionType = 3
	PodCmd_Attach         PodCmd_ActionType = 4
	PodCmd_Log            PodCmd_ActionType = 5
	PodCmd_PortForward    PodCmd_ActionType = 6
)

var PodCmd_ActionType_name = map[int32]string{
	0: "CreateOrUpdate",
	1: "Delete",
	2: "List",
	3: "Exec",
	4: "Attach",
	5: "Log",
	6: "PortForward",
}
var PodCmd_ActionType_value = map[string]int32{
	"CreateOrUpdate": 0,
	"Delete":         1,
	"List":           2,
	"Exec":           3,
	"Attach":         4,
	"Log":            5,
	"PortForward":    6,
}

func (x PodCmd_ActionType) String() string {
	return proto.EnumName(PodCmd_ActionType_name, int32(x))
}
func (PodCmd_ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pod_b7467315d22ba53a, []int{2, 0}
}

type PodInfo struct {
	Phase                PodInfo_Phase `protobuf:"varint,1,opt,name=phase,proto3,enum=connectivity.PodInfo_Phase" json:"phase,omitempty"`
	Spec                 []byte        `protobuf:"bytes,10,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               []byte        `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PodInfo) Reset()         { *m = PodInfo{} }
func (m *PodInfo) String() string { return proto.CompactTextString(m) }
func (*PodInfo) ProtoMessage()    {}
func (*PodInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_b7467315d22ba53a, []int{0}
}
func (m *PodInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodInfo.Unmarshal(m, b)
}
func (m *PodInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodInfo.Marshal(b, m, deterministic)
}
func (dst *PodInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodInfo.Merge(dst, src)
}
func (m *PodInfo) XXX_Size() int {
	return xxx_messageInfo_PodInfo.Size(m)
}
func (m *PodInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PodInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PodInfo proto.InternalMessageInfo

func (m *PodInfo) GetPhase() PodInfo_Phase {
	if m != nil {
		return m.Phase
	}
	return PodInfo_Created
}

func (m *PodInfo) GetSpec() []byte {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *PodInfo) GetStatus() []byte {
	if m != nil {
		return m.Status
	}
	return nil
}

type PodIdentity struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodIdentity) Reset()         { *m = PodIdentity{} }
func (m *PodIdentity) String() string { return proto.CompactTextString(m) }
func (*PodIdentity) ProtoMessage()    {}
func (*PodIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_b7467315d22ba53a, []int{1}
}
func (m *PodIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodIdentity.Unmarshal(m, b)
}
func (m *PodIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodIdentity.Marshal(b, m, deterministic)
}
func (dst *PodIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodIdentity.Merge(dst, src)
}
func (m *PodIdentity) XXX_Size() int {
	return xxx_messageInfo_PodIdentity.Size(m)
}
func (m *PodIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_PodIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_PodIdentity proto.InternalMessageInfo

func (m *PodIdentity) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PodIdentity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PodCmd struct {
	Id     *PodIdentity      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action PodCmd_ActionType `protobuf:"varint,2,opt,name=action,proto3,enum=connectivity.PodCmd_ActionType" json:"action,omitempty"`
	// Types that are valid to be assigned to Options:
	//	*PodCmd_CreateOptions
	//	*PodCmd_DeleteOptions
	//	*PodCmd_ListOptions
	//	*PodCmd_LogOptions
	//	*PodCmd_ExecOptions
	//	*PodCmd_PortForwardOptions
	Options              isPodCmd_Options `protobuf_oneof:"options"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PodCmd) Reset()         { *m = PodCmd{} }
func (m *PodCmd) String() string { return proto.CompactTextString(m) }
func (*PodCmd) ProtoMessage()    {}
func (*PodCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_b7467315d22ba53a, []int{2}
}
func (m *PodCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodCmd.Unmarshal(m, b)
}
func (m *PodCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodCmd.Marshal(b, m, deterministic)
}
func (dst *PodCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodCmd.Merge(dst, src)
}
func (m *PodCmd) XXX_Size() int {
	return xxx_messageInfo_PodCmd.Size(m)
}
func (m *PodCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_PodCmd.DiscardUnknown(m)
}

var xxx_messageInfo_PodCmd proto.InternalMessageInfo

func (m *PodCmd) GetId() *PodIdentity {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PodCmd) GetAction() PodCmd_ActionType {
	if m != nil {
		return m.Action
	}
	return PodCmd_CreateOrUpdate
}

type isPodCmd_Options interface {
	isPodCmd_Options()
}

type PodCmd_CreateOptions struct {
	CreateOptions *PodCreateOptions `protobuf:"bytes,11,opt,name=create_options,json=createOptions,proto3,oneof"`
}

type PodCmd_DeleteOptions struct {
	DeleteOptions *PodDeleteOptions `protobuf:"bytes,12,opt,name=delete_options,json=deleteOptions,proto3,oneof"`
}

type PodCmd_ListOptions struct {
	ListOptions *PodListOptions `protobuf:"bytes,13,opt,name=list_options,json=listOptions,proto3,oneof"`
}

type PodCmd_LogOptions struct {
	LogOptions *PodLogOptions `protobuf:"bytes,14,opt,name=log_options,json=logOptions,proto3,oneof"`
}

type PodCmd_ExecOptions struct {
	ExecOptions *PodExecOptions `protobuf:"bytes,15,opt,name=exec_options,json=execOptions,proto3,oneof"`
}

type PodCmd_PortForwardOptions struct {
	PortForwardOptions *PodPortForwardOptions `protobuf:"bytes,16,opt,name=port_forward_options,json=portForwardOptions,proto3,oneof"`
}

func (*PodCmd_CreateOptions) isPodCmd_Options() {}

func (*PodCmd_DeleteOptions) isPodCmd_Options() {}

func (*PodCmd_ListOptions) isPodCmd_Options() {}

func (*PodCmd_LogOptions) isPodCmd_Options() {}

func (*PodCmd_ExecOptions) isPodCmd_Options() {}

func (*PodCmd_PortForwardOptions) isPodCmd_Options() {}

func (m *PodCmd) GetOptions() isPodCmd_Options {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *PodCmd) GetCreateOptions() *PodCreateOptions {
	if x, ok := m.GetOptions().(*PodCmd_CreateOptions); ok {
		return x.CreateOptions
	}
	return nil
}

func (m *PodCmd) GetDeleteOptions() *PodDeleteOptions {
	if x, ok := m.GetOptions().(*PodCmd_DeleteOptions); ok {
		return x.DeleteOptions
	}
	return nil
}

func (m *PodCmd) GetListOptions() *PodListOptions {
	if x, ok := m.GetOptions().(*PodCmd_ListOptions); ok {
		return x.ListOptions
	}
	return nil
}

func (m *PodCmd) GetLogOptions() *PodLogOptions {
	if x, ok := m.GetOptions().(*PodCmd_LogOptions); ok {
		return x.LogOptions
	}
	return nil
}

func (m *PodCmd) GetExecOptions() *PodExecOptions {
	if x, ok := m.GetOptions().(*PodCmd_ExecOptions); ok {
		return x.ExecOptions
	}
	return nil
}

func (m *PodCmd) GetPortForwardOptions() *PodPortForwardOptions {
	if x, ok := m.GetOptions().(*PodCmd_PortForwardOptions); ok {
		return x.PortForwardOptions
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PodCmd) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PodCmd_OneofMarshaler, _PodCmd_OneofUnmarshaler, _PodCmd_OneofSizer, []interface{}{
		(*PodCmd_CreateOptions)(nil),
		(*PodCmd_DeleteOptions)(nil),
		(*PodCmd_ListOptions)(nil),
		(*PodCmd_LogOptions)(nil),
		(*PodCmd_ExecOptions)(nil),
		(*PodCmd_PortForwardOptions)(nil),
	}
}

func _PodCmd_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PodCmd)
	// options
	switch x := m.Options.(type) {
	case *PodCmd_CreateOptions:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateOptions); err != nil {
			return err
		}
	case *PodCmd_DeleteOptions:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeleteOptions); err != nil {
			return err
		}
	case *PodCmd_ListOptions:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ListOptions); err != nil {
			return err
		}
	case *PodCmd_LogOptions:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LogOptions); err != nil {
			return err
		}
	case *PodCmd_ExecOptions:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExecOptions); err != nil {
			return err
		}
	case *PodCmd_PortForwardOptions:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PortForwardOptions); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PodCmd.Options has unexpected type %T", x)
	}
	return nil
}

func _PodCmd_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PodCmd)
	switch tag {
	case 11: // options.create_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PodCreateOptions)
		err := b.DecodeMessage(msg)
		m.Options = &PodCmd_CreateOptions{msg}
		return true, err
	case 12: // options.delete_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PodDeleteOptions)
		err := b.DecodeMessage(msg)
		m.Options = &PodCmd_DeleteOptions{msg}
		return true, err
	case 13: // options.list_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PodListOptions)
		err := b.DecodeMessage(msg)
		m.Options = &PodCmd_ListOptions{msg}
		return true, err
	case 14: // options.log_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PodLogOptions)
		err := b.DecodeMessage(msg)
		m.Options = &PodCmd_LogOptions{msg}
		return true, err
	case 15: // options.exec_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PodExecOptions)
		err := b.DecodeMessage(msg)
		m.Options = &PodCmd_ExecOptions{msg}
		return true, err
	case 16: // options.port_forward_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PodPortForwardOptions)
		err := b.DecodeMessage(msg)
		m.Options = &PodCmd_PortForwardOptions{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PodCmd_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PodCmd)
	// options
	switch x := m.Options.(type) {
	case *PodCmd_CreateOptions:
		s := proto.Size(x.CreateOptions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_DeleteOptions:
		s := proto.Size(x.DeleteOptions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_ListOptions:
		s := proto.Size(x.ListOptions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_LogOptions:
		s := proto.Size(x.LogOptions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_ExecOptions:
		s := proto.Size(x.ExecOptions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_PortForwardOptions:
		s := proto.Size(x.PortForwardOptions)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PodCreateOptions struct {
	// protobuf bytes of PodSpec
	Spec                 []byte   `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodCreateOptions) Reset()         { *m = PodCreateOptions{} }
func (m *PodCreateOptions) String() string { return proto.CompactTextString(m) }
func (*PodCreateOptions) ProtoMessage()    {}
func (*PodCreateOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_b7467315d22ba53a, []int{3}
}
func (m *PodCreateOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodCreateOptions.Unmarshal(m, b)
}
func (m *PodCreateOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodCreateOptions.Marshal(b, m, deterministic)
}
func (dst *PodCreateOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodCreateOptions.Merge(dst, src)
}
func (m *PodCreateOptions) XXX_Size() int {
	return xxx_messageInfo_PodCreateOptions.Size(m)
}
func (m *PodCreateOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_PodCreateOptions.DiscardUnknown(m)
}

var xxx_messageInfo_PodCreateOptions proto.InternalMessageInfo

func (m *PodCreateOptions) GetSpec() []byte {
	if m != nil {
		return m.Spec
	}
	return nil
}

type PodDeleteOptions struct {
	GraceTime            int64    `protobuf:"varint,1,opt,name=grace_time,json=graceTime,proto3" json:"grace_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodDeleteOptions) Reset()         { *m = PodDeleteOptions{} }
func (m *PodDeleteOptions) String() string { return proto.CompactTextString(m) }
func (*PodDeleteOptions) ProtoMessage()    {}
func (*PodDeleteOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_b7467315d22ba53a, []int{4}
}
func (m *PodDeleteOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodDeleteOptions.Unmarshal(m, b)
}
func (m *PodDeleteOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodDeleteOptions.Marshal(b, m, deterministic)
}
func (dst *PodDeleteOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodDeleteOptions.Merge(dst, src)
}
func (m *PodDeleteOptions) XXX_Size() int {
	return xxx_messageInfo_PodDeleteOptions.Size(m)
}
func (m *PodDeleteOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_PodDeleteOptions.DiscardUnknown(m)
}

var xxx_messageInfo_PodDeleteOptions proto.InternalMessageInfo

func (m *PodDeleteOptions) GetGraceTime() int64 {
	if m != nil {
		return m.GraceTime
	}
	return 0
}

type PodListOptions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodListOptions) Reset()         { *m = PodListOptions{} }
func (m *PodListOptions) String() string { return proto.CompactTextString(m) }
func (*PodListOptions) ProtoMessage()    {}
func (*PodListOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_b7467315d22ba53a, []int{5}
}
func (m *PodListOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodListOptions.Unmarshal(m, b)
}
func (m *PodListOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodListOptions.Marshal(b, m, deterministic)
}
func (dst *PodListOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodListOptions.Merge(dst, src)
}
func (m *PodListOptions) XXX_Size() int {
	return xxx_messageInfo_PodListOptions.Size(m)
}
func (m *PodListOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_PodListOptions.DiscardUnknown(m)
}

var xxx_messageInfo_PodListOptions proto.InternalMessageInfo

type PodLogOptions struct {
	ContainerName        string   `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodLogOptions) Reset()         { *m = PodLogOptions{} }
func (m *PodLogOptions) String() string { return proto.CompactTextString(m) }
func (*PodLogOptions) ProtoMessage()    {}
func (*PodLogOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_b7467315d22ba53a, []int{6}
}
func (m *PodLogOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodLogOptions.Unmarshal(m, b)
}
func (m *PodLogOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodLogOptions.Marshal(b, m, deterministic)
}
func (dst *PodLogOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodLogOptions.Merge(dst, src)
}
func (m *PodLogOptions) XXX_Size() int {
	return xxx_messageInfo_PodLogOptions.Size(m)
}
func (m *PodLogOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_PodLogOptions.DiscardUnknown(m)
}

var xxx_messageInfo_PodLogOptions proto.InternalMessageInfo

func (m *PodLogOptions) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

type PodExecOptions struct {
	ContainerName        string   `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Command              []string `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Tty                  bool     `protobuf:"varint,11,opt,name=tty,proto3" json:"tty,omitempty"`
	Stdin                bool     `protobuf:"varint,12,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Stdout               bool     `protobuf:"varint,13,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               bool     `protobuf:"varint,14,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Cols                 int32    `protobuf:"varint,15,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows                 int32    `protobuf:"varint,16,opt,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodExecOptions) Reset()         { *m = PodExecOptions{} }
func (m *PodExecOptions) String() string { return proto.CompactTextString(m) }
func (*PodExecOptions) ProtoMessage()    {}
func (*PodExecOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_b7467315d22ba53a, []int{7}
}
func (m *PodExecOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodExecOptions.Unmarshal(m, b)
}
func (m *PodExecOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodExecOptions.Marshal(b, m, deterministic)
}
func (dst *PodExecOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodExecOptions.Merge(dst, src)
}
func (m *PodExecOptions) XXX_Size() int {
	return xxx_messageInfo_PodExecOptions.Size(m)
}
func (m *PodExecOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_PodExecOptions.DiscardUnknown(m)
}

var xxx_messageInfo_PodExecOptions proto.InternalMessageInfo

func (m *PodExecOptions) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *PodExecOptions) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *PodExecOptions) GetTty() bool {
	if m != nil {
		return m.Tty
	}
	return false
}

func (m *PodExecOptions) GetStdin() bool {
	if m != nil {
		return m.Stdin
	}
	return false
}

func (m *PodExecOptions) GetStdout() bool {
	if m != nil {
		return m.Stdout
	}
	return false
}

func (m *PodExecOptions) GetStderr() bool {
	if m != nil {
		return m.Stderr
	}
	return false
}

func (m *PodExecOptions) GetCols() int32 {
	if m != nil {
		return m.Cols
	}
	return 0
}

func (m *PodExecOptions) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

type PodPortForwardOptions struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodPortForwardOptions) Reset()         { *m = PodPortForwardOptions{} }
func (m *PodPortForwardOptions) String() string { return proto.CompactTextString(m) }
func (*PodPortForwardOptions) ProtoMessage()    {}
func (*PodPortForwardOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_b7467315d22ba53a, []int{8}
}
func (m *PodPortForwardOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodPortForwardOptions.Unmarshal(m, b)
}
func (m *PodPortForwardOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodPortForwardOptions.Marshal(b, m, deterministic)
}
func (dst *PodPortForwardOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodPortForwardOptions.Merge(dst, src)
}
func (m *PodPortForwardOptions) XXX_Size() int {
	return xxx_messageInfo_PodPortForwardOptions.Size(m)
}
func (m *PodPortForwardOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_PodPortForwardOptions.DiscardUnknown(m)
}

var xxx_messageInfo_PodPortForwardOptions proto.InternalMessageInfo

func (m *PodPortForwardOptions) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type PodData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodData) Reset()         { *m = PodData{} }
func (m *PodData) String() string { return proto.CompactTextString(m) }
func (*PodData) ProtoMessage()    {}
func (*PodData) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_b7467315d22ba53a, []int{9}
}
func (m *PodData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodData.Unmarshal(m, b)
}
func (m *PodData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodData.Marshal(b, m, deterministic)
}
func (dst *PodData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodData.Merge(dst, src)
}
func (m *PodData) XXX_Size() int {
	return xxx_messageInfo_PodData.Size(m)
}
func (m *PodData) XXX_DiscardUnknown() {
	xxx_messageInfo_PodData.DiscardUnknown(m)
}

var xxx_messageInfo_PodData proto.InternalMessageInfo

func (m *PodData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PodInfo)(nil), "connectivity.PodInfo")
	proto.RegisterType((*PodIdentity)(nil), "connectivity.PodIdentity")
	proto.RegisterType((*PodCmd)(nil), "connectivity.PodCmd")
	proto.RegisterType((*PodCreateOptions)(nil), "connectivity.PodCreateOptions")
	proto.RegisterType((*PodDeleteOptions)(nil), "connectivity.PodDeleteOptions")
	proto.RegisterType((*PodListOptions)(nil), "connectivity.PodListOptions")
	proto.RegisterType((*PodLogOptions)(nil), "connectivity.PodLogOptions")
	proto.RegisterType((*PodExecOptions)(nil), "connectivity.PodExecOptions")
	proto.RegisterType((*PodPortForwardOptions)(nil), "connectivity.PodPortForwardOptions")
	proto.RegisterType((*PodData)(nil), "connectivity.PodData")
	proto.RegisterEnum("connectivity.PodInfo_Phase", PodInfo_Phase_name, PodInfo_Phase_value)
	proto.RegisterEnum("connectivity.PodCmd_ActionType", PodCmd_ActionType_name, PodCmd_ActionType_value)
}

func init() { proto.RegisterFile("pod.proto", fileDescriptor_pod_b7467315d22ba53a) }

var fileDescriptor_pod_b7467315d22ba53a = []byte{
	// 651 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xed, 0x6a, 0x13, 0x41,
	0x14, 0xed, 0x26, 0xdd, 0x7c, 0xdc, 0x24, 0xdb, 0x65, 0xa8, 0x12, 0xb1, 0xd5, 0xb2, 0xa2, 0x54,
	0x84, 0x40, 0x23, 0xe8, 0x0f, 0x41, 0xa9, 0xad, 0x5f, 0x50, 0x34, 0x0c, 0x15, 0x7f, 0x86, 0x71,
	0x66, 0x9a, 0x2e, 0x64, 0x67, 0x96, 0xd9, 0xa9, 0x6d, 0xde, 0xc2, 0x97, 0xf0, 0x81, 0x7c, 0x23,
	0x99, 0x3b, 0xdb, 0xdd, 0xd4, 0xb5, 0xe0, 0xbf, 0x7b, 0xce, 0x9c, 0x3d, 0x7b, 0xe7, 0x7e, 0x0c,
	0xf4, 0x73, 0x2d, 0x26, 0xb9, 0xd1, 0x56, 0x93, 0x21, 0xd7, 0x4a, 0x49, 0x6e, 0xd3, 0x1f, 0xa9,
	0x5d, 0x25, 0xbf, 0x02, 0xe8, 0xce, 0xb4, 0xf8, 0xa4, 0xce, 0x34, 0x39, 0x80, 0x30, 0x3f, 0x67,
	0x85, 0x1c, 0x07, 0x7b, 0xc1, 0x7e, 0x34, 0xbd, 0x3f, 0x59, 0x57, 0x4e, 0x4a, 0xd5, 0x64, 0xe6,
	0x24, 0xd4, 0x2b, 0x09, 0x81, 0xcd, 0x22, 0x97, 0x7c, 0x0c, 0x7b, 0xc1, 0xfe, 0x90, 0x62, 0x4c,
	0xee, 0x42, 0xa7, 0xb0, 0xcc, 0x5e, 0x14, 0xe3, 0x01, 0xb2, 0x25, 0x4a, 0x5e, 0x41, 0x88, 0xdf,
	0x92, 0x01, 0x74, 0x8f, 0x8c, 0x64, 0x56, 0x8a, 0x78, 0xc3, 0x01, 0x7a, 0xa1, 0x54, 0xaa, 0x16,
	0x71, 0xe0, 0xc0, 0xb1, 0x5c, 0x4a, 0x77, 0xd2, 0x72, 0xe0, 0x6b, 0x2e, 0x50, 0xd6, 0x4e, 0xde,
	0xc0, 0xc0, 0x25, 0x20, 0xa4, 0xb2, 0xa9, 0x5d, 0x91, 0x1d, 0xe8, 0x2b, 0x96, 0xc9, 0x22, 0x67,
	0xdc, 0xa7, 0xdb, 0xa7, 0x35, 0xe1, 0xb2, 0x72, 0x60, 0xdc, 0xc2, 0x03, 0x8c, 0x93, 0x9f, 0x21,
	0x74, 0x66, 0x5a, 0x1c, 0x65, 0x82, 0x3c, 0x85, 0x56, 0x2a, 0xf0, 0xab, 0xc1, 0xf4, 0x5e, 0xf3,
	0x92, 0xe5, 0x3f, 0x68, 0x2b, 0x15, 0xe4, 0x25, 0x74, 0x18, 0xb7, 0xa9, 0x56, 0xe8, 0x15, 0x4d,
	0x1f, 0x36, 0xe4, 0x47, 0x99, 0x98, 0x1c, 0xa2, 0xe4, 0x74, 0x95, 0x4b, 0x5a, 0xca, 0xc9, 0x07,
	0x88, 0x38, 0xde, 0x71, 0xae, 0x73, 0x47, 0xf8, 0x62, 0x0c, 0xa6, 0x0f, 0x9a, 0x06, 0x28, 0xfb,
	0xe2, 0x55, 0x1f, 0x37, 0xe8, 0x88, 0xaf, 0x13, 0xce, 0x48, 0x60, 0x49, 0x2a, 0xa3, 0xe1, 0x2d,
	0x46, 0xbe, 0x72, 0x6b, 0x46, 0x62, 0x9d, 0x20, 0x87, 0x30, 0x5c, 0xa6, 0x85, 0xad, 0x6c, 0x46,
	0x68, 0xb3, 0xd3, 0xb0, 0x39, 0x49, 0x0b, 0x5b, 0x9b, 0x0c, 0x96, 0x35, 0x24, 0xaf, 0x61, 0xb0,
	0xd4, 0x8b, 0xca, 0x21, 0x42, 0x87, 0xe6, 0x98, 0x9c, 0xe8, 0x45, 0x6d, 0x00, 0xcb, 0x0a, 0xb9,
	0x14, 0xe4, 0x95, 0xe4, 0x95, 0xc1, 0xd6, 0x2d, 0x29, 0xbc, 0xbb, 0x92, 0x7c, 0x2d, 0x05, 0x59,
	0x43, 0xf2, 0x0d, 0xb6, 0x73, 0x6d, 0xec, 0xfc, 0x4c, 0x9b, 0x4b, 0x66, 0x44, 0x65, 0x15, 0xa3,
	0xd5, 0xa3, 0x86, 0xd5, 0x4c, 0x1b, 0xfb, 0xde, 0x6b, 0x6b, 0x47, 0x92, 0x37, 0xd8, 0xe4, 0x0c,
	0xa0, 0x6e, 0x23, 0x21, 0x10, 0x95, 0x7d, 0x31, 0x7e, 0x06, 0xe3, 0x0d, 0x02, 0xd0, 0xf1, 0x25,
	0x8e, 0x03, 0xd2, 0x83, 0x4d, 0x57, 0xa7, 0xb8, 0xe5, 0x22, 0x97, 0x6e, 0xdc, 0x76, 0xe7, 0x87,
	0xd6, 0x32, 0x7e, 0x1e, 0x6f, 0x92, 0x2e, 0xb4, 0x4f, 0xf4, 0x22, 0x0e, 0xc9, 0x96, 0x9b, 0xdb,
	0xea, 0x67, 0x71, 0xe7, 0x6d, 0x1f, 0xba, 0x65, 0xce, 0xc9, 0x13, 0x88, 0xff, 0xee, 0x7f, 0xb5,
	0x50, 0x41, 0xbd, 0x50, 0xc9, 0x01, 0xea, 0x6e, 0xb4, 0x97, 0xec, 0x02, 0x2c, 0x0c, 0xe3, 0x72,
	0x6e, 0xd3, 0xcc, 0x6f, 0x40, 0x9b, 0xf6, 0x91, 0x39, 0x4d, 0x33, 0x99, 0xc4, 0x10, 0xdd, 0x6c,
	0x65, 0xf2, 0x02, 0x46, 0x37, 0x5a, 0x43, 0x1e, 0x43, 0xc4, 0xb5, 0xb2, 0x2c, 0x55, 0xd2, 0xcc,
	0x71, 0x5d, 0xfc, 0x1e, 0x8d, 0x2a, 0xf6, 0xb3, 0xdb, 0x9b, 0xdf, 0x01, 0x5a, 0xad, 0xb5, 0xe4,
	0x3f, 0xbf, 0x24, 0x63, 0xe8, 0x72, 0x9d, 0x65, 0x4c, 0x89, 0x71, 0x6b, 0xaf, 0xbd, 0xdf, 0xa7,
	0xd7, 0x90, 0xc4, 0xd0, 0xb6, 0x76, 0x85, 0x1b, 0xd1, 0xa3, 0x2e, 0x24, 0xdb, 0x10, 0x16, 0x56,
	0xa4, 0x0a, 0x87, 0xbb, 0x47, 0x3d, 0xf0, 0x2f, 0x89, 0xd0, 0x17, 0x16, 0x87, 0xb5, 0x47, 0x4b,
	0x54, 0xf2, 0xd2, 0x18, 0x1c, 0x41, 0xcf, 0x4b, 0x63, 0x5c, 0xf1, 0xb8, 0x5e, 0xfa, 0xb9, 0x0a,
	0x29, 0xc6, 0x8e, 0x33, 0xfa, 0xd2, 0x0f, 0x48, 0x48, 0x31, 0x4e, 0x9e, 0xc1, 0x9d, 0x7f, 0x8e,
	0x86, 0x13, 0xbb, 0xd1, 0xc0, 0xfb, 0x84, 0x14, 0xe3, 0x64, 0x17, 0x1f, 0xc8, 0x63, 0x66, 0x99,
	0x3b, 0x16, 0xcc, 0xb2, 0xeb, 0xe6, 0xb8, 0xf8, 0x7b, 0x07, 0x5f, 0xd5, 0xe7, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xa6, 0xa6, 0x46, 0x41, 0x62, 0x05, 0x00, 0x00,
}
