// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pod.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PodStatus struct {
	// Types that are valid to be assigned to Status:
	//	*PodStatus_Created
	//	*PodStatus_Updated
	//	*PodStatus_Deleted
	//	*PodStatus_Info
	Status               isPodStatus_Status `protobuf_oneof:"status"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PodStatus) Reset()         { *m = PodStatus{} }
func (m *PodStatus) String() string { return proto.CompactTextString(m) }
func (*PodStatus) ProtoMessage()    {}
func (*PodStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_2366163e9d9c98e3, []int{0}
}
func (m *PodStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodStatus.Unmarshal(m, b)
}
func (m *PodStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodStatus.Marshal(b, m, deterministic)
}
func (dst *PodStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodStatus.Merge(dst, src)
}
func (m *PodStatus) XXX_Size() int {
	return xxx_messageInfo_PodStatus.Size(m)
}
func (m *PodStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PodStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PodStatus proto.InternalMessageInfo

type isPodStatus_Status interface {
	isPodStatus_Status()
}

type PodStatus_Created struct {
	Created *PodCreated `protobuf:"bytes,1,opt,name=created,proto3,oneof"`
}

type PodStatus_Updated struct {
	Updated *PodUpdated `protobuf:"bytes,2,opt,name=updated,proto3,oneof"`
}

type PodStatus_Deleted struct {
	Deleted *PodDeleted `protobuf:"bytes,3,opt,name=deleted,proto3,oneof"`
}

type PodStatus_Info struct {
	Info *PodInfo `protobuf:"bytes,4,opt,name=info,proto3,oneof"`
}

func (*PodStatus_Created) isPodStatus_Status() {}

func (*PodStatus_Updated) isPodStatus_Status() {}

func (*PodStatus_Deleted) isPodStatus_Status() {}

func (*PodStatus_Info) isPodStatus_Status() {}

func (m *PodStatus) GetStatus() isPodStatus_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PodStatus) GetCreated() *PodCreated {
	if x, ok := m.GetStatus().(*PodStatus_Created); ok {
		return x.Created
	}
	return nil
}

func (m *PodStatus) GetUpdated() *PodUpdated {
	if x, ok := m.GetStatus().(*PodStatus_Updated); ok {
		return x.Updated
	}
	return nil
}

func (m *PodStatus) GetDeleted() *PodDeleted {
	if x, ok := m.GetStatus().(*PodStatus_Deleted); ok {
		return x.Deleted
	}
	return nil
}

func (m *PodStatus) GetInfo() *PodInfo {
	if x, ok := m.GetStatus().(*PodStatus_Info); ok {
		return x.Info
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PodStatus) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PodStatus_OneofMarshaler, _PodStatus_OneofUnmarshaler, _PodStatus_OneofSizer, []interface{}{
		(*PodStatus_Created)(nil),
		(*PodStatus_Updated)(nil),
		(*PodStatus_Deleted)(nil),
		(*PodStatus_Info)(nil),
	}
}

func _PodStatus_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PodStatus)
	// status
	switch x := m.Status.(type) {
	case *PodStatus_Created:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Created); err != nil {
			return err
		}
	case *PodStatus_Updated:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Updated); err != nil {
			return err
		}
	case *PodStatus_Deleted:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Deleted); err != nil {
			return err
		}
	case *PodStatus_Info:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Info); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PodStatus.Status has unexpected type %T", x)
	}
	return nil
}

func _PodStatus_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PodStatus)
	switch tag {
	case 1: // status.created
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PodCreated)
		err := b.DecodeMessage(msg)
		m.Status = &PodStatus_Created{msg}
		return true, err
	case 2: // status.updated
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PodUpdated)
		err := b.DecodeMessage(msg)
		m.Status = &PodStatus_Updated{msg}
		return true, err
	case 3: // status.deleted
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PodDeleted)
		err := b.DecodeMessage(msg)
		m.Status = &PodStatus_Deleted{msg}
		return true, err
	case 4: // status.info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PodInfo)
		err := b.DecodeMessage(msg)
		m.Status = &PodStatus_Info{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PodStatus_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PodStatus)
	// status
	switch x := m.Status.(type) {
	case *PodStatus_Created:
		s := proto.Size(x.Created)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodStatus_Updated:
		s := proto.Size(x.Updated)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodStatus_Deleted:
		s := proto.Size(x.Deleted)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodStatus_Info:
		s := proto.Size(x.Info)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PodDeleted struct {
	Pod                  string   `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodDeleted) Reset()         { *m = PodDeleted{} }
func (m *PodDeleted) String() string { return proto.CompactTextString(m) }
func (*PodDeleted) ProtoMessage()    {}
func (*PodDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_2366163e9d9c98e3, []int{1}
}
func (m *PodDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodDeleted.Unmarshal(m, b)
}
func (m *PodDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodDeleted.Marshal(b, m, deterministic)
}
func (dst *PodDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodDeleted.Merge(dst, src)
}
func (m *PodDeleted) XXX_Size() int {
	return xxx_messageInfo_PodDeleted.Size(m)
}
func (m *PodDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_PodDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_PodDeleted proto.InternalMessageInfo

func (m *PodDeleted) GetPod() string {
	if m != nil {
		return m.Pod
	}
	return ""
}

type PodCreated struct {
	Pod                  string   `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodCreated) Reset()         { *m = PodCreated{} }
func (m *PodCreated) String() string { return proto.CompactTextString(m) }
func (*PodCreated) ProtoMessage()    {}
func (*PodCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_2366163e9d9c98e3, []int{2}
}
func (m *PodCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodCreated.Unmarshal(m, b)
}
func (m *PodCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodCreated.Marshal(b, m, deterministic)
}
func (dst *PodCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodCreated.Merge(dst, src)
}
func (m *PodCreated) XXX_Size() int {
	return xxx_messageInfo_PodCreated.Size(m)
}
func (m *PodCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_PodCreated.DiscardUnknown(m)
}

var xxx_messageInfo_PodCreated proto.InternalMessageInfo

func (m *PodCreated) GetPod() string {
	if m != nil {
		return m.Pod
	}
	return ""
}

type PodUpdated struct {
	Pod                  string   `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodUpdated) Reset()         { *m = PodUpdated{} }
func (m *PodUpdated) String() string { return proto.CompactTextString(m) }
func (*PodUpdated) ProtoMessage()    {}
func (*PodUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_2366163e9d9c98e3, []int{3}
}
func (m *PodUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodUpdated.Unmarshal(m, b)
}
func (m *PodUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodUpdated.Marshal(b, m, deterministic)
}
func (dst *PodUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodUpdated.Merge(dst, src)
}
func (m *PodUpdated) XXX_Size() int {
	return xxx_messageInfo_PodUpdated.Size(m)
}
func (m *PodUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_PodUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_PodUpdated proto.InternalMessageInfo

func (m *PodUpdated) GetPod() string {
	if m != nil {
		return m.Pod
	}
	return ""
}

type PodInfo struct {
	Pod                  string   `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodInfo) Reset()         { *m = PodInfo{} }
func (m *PodInfo) String() string { return proto.CompactTextString(m) }
func (*PodInfo) ProtoMessage()    {}
func (*PodInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_2366163e9d9c98e3, []int{4}
}
func (m *PodInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodInfo.Unmarshal(m, b)
}
func (m *PodInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodInfo.Marshal(b, m, deterministic)
}
func (dst *PodInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodInfo.Merge(dst, src)
}
func (m *PodInfo) XXX_Size() int {
	return xxx_messageInfo_PodInfo.Size(m)
}
func (m *PodInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PodInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PodInfo proto.InternalMessageInfo

func (m *PodInfo) GetPod() string {
	if m != nil {
		return m.Pod
	}
	return ""
}

type PodCmd struct {
	// Types that are valid to be assigned to Cmd:
	//	*PodCmd_CreateOrUpdate
	//	*PodCmd_Delete
	//	*PodCmd_Get
	//	*PodCmd_Log
	Cmd                  isPodCmd_Cmd `protobuf_oneof:"cmd"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PodCmd) Reset()         { *m = PodCmd{} }
func (m *PodCmd) String() string { return proto.CompactTextString(m) }
func (*PodCmd) ProtoMessage()    {}
func (*PodCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_2366163e9d9c98e3, []int{5}
}
func (m *PodCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodCmd.Unmarshal(m, b)
}
func (m *PodCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodCmd.Marshal(b, m, deterministic)
}
func (dst *PodCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodCmd.Merge(dst, src)
}
func (m *PodCmd) XXX_Size() int {
	return xxx_messageInfo_PodCmd.Size(m)
}
func (m *PodCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_PodCmd.DiscardUnknown(m)
}

var xxx_messageInfo_PodCmd proto.InternalMessageInfo

type isPodCmd_Cmd interface {
	isPodCmd_Cmd()
}

type PodCmd_CreateOrUpdate struct {
	CreateOrUpdate *CmdCreateOrUpdatePod `protobuf:"bytes,1,opt,name=create_or_update,json=createOrUpdate,proto3,oneof"`
}

type PodCmd_Delete struct {
	Delete *CmdDeletePod `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

type PodCmd_Get struct {
	Get *CmdListPods `protobuf:"bytes,3,opt,name=get,proto3,oneof"`
}

type PodCmd_Log struct {
	Log *CmdGetPodLog `protobuf:"bytes,4,opt,name=log,proto3,oneof"`
}

func (*PodCmd_CreateOrUpdate) isPodCmd_Cmd() {}

func (*PodCmd_Delete) isPodCmd_Cmd() {}

func (*PodCmd_Get) isPodCmd_Cmd() {}

func (*PodCmd_Log) isPodCmd_Cmd() {}

func (m *PodCmd) GetCmd() isPodCmd_Cmd {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (m *PodCmd) GetCreateOrUpdate() *CmdCreateOrUpdatePod {
	if x, ok := m.GetCmd().(*PodCmd_CreateOrUpdate); ok {
		return x.CreateOrUpdate
	}
	return nil
}

func (m *PodCmd) GetDelete() *CmdDeletePod {
	if x, ok := m.GetCmd().(*PodCmd_Delete); ok {
		return x.Delete
	}
	return nil
}

func (m *PodCmd) GetGet() *CmdListPods {
	if x, ok := m.GetCmd().(*PodCmd_Get); ok {
		return x.Get
	}
	return nil
}

func (m *PodCmd) GetLog() *CmdGetPodLog {
	if x, ok := m.GetCmd().(*PodCmd_Log); ok {
		return x.Log
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PodCmd) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PodCmd_OneofMarshaler, _PodCmd_OneofUnmarshaler, _PodCmd_OneofSizer, []interface{}{
		(*PodCmd_CreateOrUpdate)(nil),
		(*PodCmd_Delete)(nil),
		(*PodCmd_Get)(nil),
		(*PodCmd_Log)(nil),
	}
}

func _PodCmd_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PodCmd)
	// cmd
	switch x := m.Cmd.(type) {
	case *PodCmd_CreateOrUpdate:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateOrUpdate); err != nil {
			return err
		}
	case *PodCmd_Delete:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Delete); err != nil {
			return err
		}
	case *PodCmd_Get:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Get); err != nil {
			return err
		}
	case *PodCmd_Log:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Log); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PodCmd.Cmd has unexpected type %T", x)
	}
	return nil
}

func _PodCmd_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PodCmd)
	switch tag {
	case 1: // cmd.create_or_update
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CmdCreateOrUpdatePod)
		err := b.DecodeMessage(msg)
		m.Cmd = &PodCmd_CreateOrUpdate{msg}
		return true, err
	case 2: // cmd.delete
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CmdDeletePod)
		err := b.DecodeMessage(msg)
		m.Cmd = &PodCmd_Delete{msg}
		return true, err
	case 3: // cmd.get
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CmdListPods)
		err := b.DecodeMessage(msg)
		m.Cmd = &PodCmd_Get{msg}
		return true, err
	case 4: // cmd.log
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CmdGetPodLog)
		err := b.DecodeMessage(msg)
		m.Cmd = &PodCmd_Log{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PodCmd_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PodCmd)
	// cmd
	switch x := m.Cmd.(type) {
	case *PodCmd_CreateOrUpdate:
		s := proto.Size(x.CreateOrUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_Delete:
		s := proto.Size(x.Delete)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_Get:
		s := proto.Size(x.Get)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PodCmd_Log:
		s := proto.Size(x.Log)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CmdCreateOrUpdatePod struct {
	PodSpec              string   `protobuf:"bytes,1,opt,name=pod_spec,json=podSpec,proto3" json:"pod_spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdCreateOrUpdatePod) Reset()         { *m = CmdCreateOrUpdatePod{} }
func (m *CmdCreateOrUpdatePod) String() string { return proto.CompactTextString(m) }
func (*CmdCreateOrUpdatePod) ProtoMessage()    {}
func (*CmdCreateOrUpdatePod) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_2366163e9d9c98e3, []int{6}
}
func (m *CmdCreateOrUpdatePod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdCreateOrUpdatePod.Unmarshal(m, b)
}
func (m *CmdCreateOrUpdatePod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdCreateOrUpdatePod.Marshal(b, m, deterministic)
}
func (dst *CmdCreateOrUpdatePod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdCreateOrUpdatePod.Merge(dst, src)
}
func (m *CmdCreateOrUpdatePod) XXX_Size() int {
	return xxx_messageInfo_CmdCreateOrUpdatePod.Size(m)
}
func (m *CmdCreateOrUpdatePod) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdCreateOrUpdatePod.DiscardUnknown(m)
}

var xxx_messageInfo_CmdCreateOrUpdatePod proto.InternalMessageInfo

func (m *CmdCreateOrUpdatePod) GetPodSpec() string {
	if m != nil {
		return m.PodSpec
	}
	return ""
}

type CmdDeletePod struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdDeletePod) Reset()         { *m = CmdDeletePod{} }
func (m *CmdDeletePod) String() string { return proto.CompactTextString(m) }
func (*CmdDeletePod) ProtoMessage()    {}
func (*CmdDeletePod) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_2366163e9d9c98e3, []int{7}
}
func (m *CmdDeletePod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdDeletePod.Unmarshal(m, b)
}
func (m *CmdDeletePod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdDeletePod.Marshal(b, m, deterministic)
}
func (dst *CmdDeletePod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdDeletePod.Merge(dst, src)
}
func (m *CmdDeletePod) XXX_Size() int {
	return xxx_messageInfo_CmdDeletePod.Size(m)
}
func (m *CmdDeletePod) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdDeletePod.DiscardUnknown(m)
}

var xxx_messageInfo_CmdDeletePod proto.InternalMessageInfo

func (m *CmdDeletePod) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CmdDeletePod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CmdListPods struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdListPods) Reset()         { *m = CmdListPods{} }
func (m *CmdListPods) String() string { return proto.CompactTextString(m) }
func (*CmdListPods) ProtoMessage()    {}
func (*CmdListPods) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_2366163e9d9c98e3, []int{8}
}
func (m *CmdListPods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdListPods.Unmarshal(m, b)
}
func (m *CmdListPods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdListPods.Marshal(b, m, deterministic)
}
func (dst *CmdListPods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdListPods.Merge(dst, src)
}
func (m *CmdListPods) XXX_Size() int {
	return xxx_messageInfo_CmdListPods.Size(m)
}
func (m *CmdListPods) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdListPods.DiscardUnknown(m)
}

var xxx_messageInfo_CmdListPods proto.InternalMessageInfo

func (m *CmdListPods) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CmdListPods) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CmdGetPodLog struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ContainerName        string   `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdGetPodLog) Reset()         { *m = CmdGetPodLog{} }
func (m *CmdGetPodLog) String() string { return proto.CompactTextString(m) }
func (*CmdGetPodLog) ProtoMessage()    {}
func (*CmdGetPodLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_pod_2366163e9d9c98e3, []int{9}
}
func (m *CmdGetPodLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdGetPodLog.Unmarshal(m, b)
}
func (m *CmdGetPodLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdGetPodLog.Marshal(b, m, deterministic)
}
func (dst *CmdGetPodLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdGetPodLog.Merge(dst, src)
}
func (m *CmdGetPodLog) XXX_Size() int {
	return xxx_messageInfo_CmdGetPodLog.Size(m)
}
func (m *CmdGetPodLog) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdGetPodLog.DiscardUnknown(m)
}

var xxx_messageInfo_CmdGetPodLog proto.InternalMessageInfo

func (m *CmdGetPodLog) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CmdGetPodLog) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CmdGetPodLog) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func init() {
	proto.RegisterType((*PodStatus)(nil), "service.PodStatus")
	proto.RegisterType((*PodDeleted)(nil), "service.PodDeleted")
	proto.RegisterType((*PodCreated)(nil), "service.PodCreated")
	proto.RegisterType((*PodUpdated)(nil), "service.PodUpdated")
	proto.RegisterType((*PodInfo)(nil), "service.PodInfo")
	proto.RegisterType((*PodCmd)(nil), "service.PodCmd")
	proto.RegisterType((*CmdCreateOrUpdatePod)(nil), "service.CmdCreateOrUpdatePod")
	proto.RegisterType((*CmdDeletePod)(nil), "service.CmdDeletePod")
	proto.RegisterType((*CmdListPods)(nil), "service.CmdListPods")
	proto.RegisterType((*CmdGetPodLog)(nil), "service.CmdGetPodLog")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PodClient is the client API for Pod service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PodClient interface {
	SyncDevicePods(ctx context.Context, opts ...grpc.CallOption) (Pod_SyncDevicePodsClient, error)
}

type podClient struct {
	cc *grpc.ClientConn
}

func NewPodClient(cc *grpc.ClientConn) PodClient {
	return &podClient{cc}
}

func (c *podClient) SyncDevicePods(ctx context.Context, opts ...grpc.CallOption) (Pod_SyncDevicePodsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Pod_serviceDesc.Streams[0], "/service.Pod/SyncDevicePods", opts...)
	if err != nil {
		return nil, err
	}
	x := &podSyncDevicePodsClient{stream}
	return x, nil
}

type Pod_SyncDevicePodsClient interface {
	Send(*PodStatus) error
	Recv() (*PodCmd, error)
	grpc.ClientStream
}

type podSyncDevicePodsClient struct {
	grpc.ClientStream
}

func (x *podSyncDevicePodsClient) Send(m *PodStatus) error {
	return x.ClientStream.SendMsg(m)
}

func (x *podSyncDevicePodsClient) Recv() (*PodCmd, error) {
	m := new(PodCmd)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PodServer is the server API for Pod service.
type PodServer interface {
	SyncDevicePods(Pod_SyncDevicePodsServer) error
}

func RegisterPodServer(s *grpc.Server, srv PodServer) {
	s.RegisterService(&_Pod_serviceDesc, srv)
}

func _Pod_SyncDevicePods_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PodServer).SyncDevicePods(&podSyncDevicePodsServer{stream})
}

type Pod_SyncDevicePodsServer interface {
	Send(*PodCmd) error
	Recv() (*PodStatus, error)
	grpc.ServerStream
}

type podSyncDevicePodsServer struct {
	grpc.ServerStream
}

func (x *podSyncDevicePodsServer) Send(m *PodCmd) error {
	return x.ServerStream.SendMsg(m)
}

func (x *podSyncDevicePodsServer) Recv() (*PodStatus, error) {
	m := new(PodStatus)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Pod_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Pod",
	HandlerType: (*PodServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncDevicePods",
			Handler:       _Pod_SyncDevicePods_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pod.proto",
}

func init() { proto.RegisterFile("pod.proto", fileDescriptor_pod_2366163e9d9c98e3) }

var fileDescriptor_pod_2366163e9d9c98e3 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x5d, 0x8b, 0xda, 0x40,
	0x14, 0x35, 0x8d, 0x4d, 0xcc, 0xb5, 0xb5, 0x32, 0xb5, 0x60, 0x3f, 0x29, 0x81, 0x16, 0xfb, 0xa2,
	0xad, 0x7d, 0xea, 0x53, 0x45, 0x85, 0x2a, 0x48, 0x37, 0x44, 0xf6, 0x39, 0x64, 0x67, 0xc6, 0x10,
	0x30, 0xb9, 0x43, 0x12, 0x17, 0xf6, 0x5f, 0xee, 0x4f, 0xd8, 0x9f, 0xb2, 0xcc, 0xc7, 0x6a, 0x44,
	0xf7, 0x61, 0xf7, 0x6d, 0x32, 0xe7, 0x9c, 0x3b, 0xe7, 0x1c, 0x72, 0xc1, 0x13, 0xc8, 0x86, 0xa2,
	0xc0, 0x0a, 0x89, 0x5b, 0xf2, 0xe2, 0x3a, 0xa5, 0xdc, 0xbf, 0xb5, 0xc0, 0x0b, 0x90, 0xad, 0xab,
	0xb8, 0xda, 0x95, 0x64, 0x04, 0x2e, 0x2d, 0x78, 0x5c, 0x71, 0xd6, 0xb7, 0xbe, 0x5a, 0x83, 0xf6,
	0xf8, 0xed, 0xd0, 0x10, 0x87, 0x01, 0xb2, 0x99, 0x86, 0x16, 0x8d, 0xf0, 0x81, 0x25, 0x05, 0x3b,
	0xc1, 0x94, 0xe0, 0xc5, 0xa9, 0xe0, 0x52, 0x43, 0x52, 0x60, 0x58, 0x52, 0xc0, 0xf8, 0x96, 0x4b,
	0x81, 0x7d, 0x2a, 0x98, 0x6b, 0x48, 0x0a, 0x0c, 0x8b, 0x7c, 0x87, 0x66, 0x9a, 0x6f, 0xb0, 0xdf,
	0x54, 0xec, 0x6e, 0x9d, 0xbd, 0xcc, 0x37, 0xb8, 0x68, 0x84, 0x0a, 0x9f, 0xb6, 0xc0, 0x29, 0x55,
	0x08, 0xff, 0x0b, 0xc0, 0x61, 0x14, 0xe9, 0x82, 0x2d, 0x50, 0xc7, 0xf1, 0x42, 0x79, 0x34, 0xb8,
	0x09, 0xf3, 0x28, 0x6e, 0xbc, 0x9f, 0xc1, 0x3f, 0x82, 0x6b, 0x1e, 0x3f, 0x03, 0xde, 0x59, 0xe0,
	0xc8, 0xe9, 0x19, 0x23, 0x4b, 0xe8, 0xea, 0x9a, 0x22, 0x2c, 0x22, 0x9d, 0xdf, 0xb4, 0xfa, 0x79,
	0x9f, 0x62, 0x96, 0x19, 0x23, 0x17, 0x85, 0x7e, 0x30, 0x40, 0x99, 0xbe, 0x43, 0x8f, 0x2e, 0xc9,
	0x08, 0x1c, 0xdd, 0x87, 0x69, 0xf9, 0x5d, 0x7d, 0x80, 0x4e, 0xaa, 0x85, 0x86, 0x46, 0x06, 0x60,
	0x27, 0xbc, 0x32, 0x15, 0xf7, 0xea, 0xec, 0x55, 0x5a, 0x56, 0x01, 0xb2, 0x72, 0xd1, 0x08, 0x25,
	0x85, 0xfc, 0x00, 0x7b, 0x8b, 0x89, 0xa9, 0xf7, 0x68, 0xee, 0x3f, 0x2e, 0x89, 0x2b, 0x4c, 0x24,
	0x75, 0x8b, 0xc9, 0xf4, 0x25, 0xd8, 0x34, 0x63, 0xfe, 0x2f, 0xe8, 0x9d, 0xb3, 0x4d, 0xde, 0x43,
	0x4b, 0x20, 0x8b, 0x4a, 0xc1, 0xa9, 0x69, 0xc4, 0x15, 0xc8, 0xd6, 0x82, 0x53, 0x7f, 0x02, 0xaf,
	0xea, 0x46, 0xc9, 0x27, 0xf0, 0xf2, 0x38, 0xe3, 0xa5, 0x88, 0x29, 0x37, 0xdc, 0xc3, 0x05, 0x21,
	0xd0, 0x94, 0x1f, 0x2a, 0xab, 0x17, 0xaa, 0xb3, 0xff, 0x17, 0xda, 0x35, 0xf3, 0xcf, 0x18, 0x90,
	0x28, 0x0b, 0xfb, 0x4c, 0x4f, 0x9f, 0x40, 0xbe, 0x41, 0x87, 0x62, 0x5e, 0xc5, 0x69, 0xce, 0x8b,
	0x48, 0xa1, 0xb6, 0x42, 0x5f, 0xef, 0x6f, 0xff, 0xc7, 0x19, 0x1f, 0x4f, 0xc0, 0x96, 0x11, 0xff,
	0x40, 0x67, 0x7d, 0x93, 0xd3, 0x39, 0x97, 0x75, 0x2a, 0xcf, 0xa4, 0xfe, 0xef, 0xea, 0x85, 0xfb,
	0xf0, 0xe6, 0x68, 0xbf, 0x32, 0x36, 0xb0, 0x7e, 0x5a, 0x57, 0x8e, 0xda, 0xd1, 0xdf, 0xf7, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x90, 0x04, 0x73, 0xab, 0xb0, 0x03, 0x00, 0x00,
}
