---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aranya
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - events
  - configmaps
  - secrets
  # aranya needs to create and manage virtual nodes and its pods for edge deivces
  - nodes
  - nodes/status
  - pods
  - pods/status
  verbs:
  - '*'
# control aranya crds
- apiGroups: [ 'aranya.arhat.dev' ]
  resources: [ '*' ]
  verbs: [ '*' ]
# required to generate node certificates
- apiGroups: [ 'certificates.k8s.io' ]
  resources: [ '*' ]
  verbs: [ '*' ]
