# 
# This deployment script deploys aranya to a dedicated namespace (iot-edge)
# 
---
apiVersion: v1
kind: Namespace
metadata:
  name: iot-edge
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aranya
  namespace: iot-edge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aranya
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      # aranya needs to create and manage virtual nodes and its pods for edge deivces
      - nodes
      - nodes/status
      - pods
      - pods/status
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - aranya.arhat.dev
    resources:
      - '*'
    verbs:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aranya
subjects:
  - kind: ServiceAccount
    name: aranya
    namespace: iot-edge
roleRef:
  kind: ClusterRole
  name: aranya
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aranya
  namespace: iot-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aranya
      arhat.dev/type: controller
  template:
    metadata:
      labels:
        name: aranya
        # required to get services working
        arhat.dev/type: controller
    spec:
      serviceAccountName: aranya
      # required to work with host network to serve as virtual node
      hostNetwork: true
      containers:
        - name: aranya
          image: arhatdev/aranya:latest
          command:
            - /app
          imagePullPolicy: Always
          env:
            # namespace to watch (also deployed to this namespace)
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "aranya"
