---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aranya
  namespace: edge
data:
  config.yaml: |-
    controller:
      log:
        level: 5
        dir: /var/log/aranya/
    virtualnode:
      connectivity:
        timers:
          unary_session_timeout: 1m
          stream_session_timeout: 4h
          force_node_status_sync_interval: 100m
          force_pod_status_sync_interval: 10m
      services:
        node:
          timers:
            status_sync_interval: 10s
        pod:
          timers:
            resync_interval: 60s
        stream:
          timers:
            idle_timeout: 4h
            creation_timeout: 30s
    services:
      metrics:
        address: "0.0.0.0"
        port: 8383
---
# this is an example deployment script for test deployment only
# use DaemonSet if possible
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aranya
  namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aranya
      arhat.dev/role: Controller
  template:
    metadata:
      labels:
        name: aranya
        # required label to get gRPC services working
        arhat.dev/role: Controller
    spec:
      serviceAccountName: aranya
      # required to work in host network mode to serve kubelet http service
      hostNetwork: true
      volumes:
      - name: config
        configMap:
          name: aranya
          optional: true
      containers:
      - name: aranya
        image: arhatdev/aranya:latest
        imagePullPolicy: Always
        command: [ "/app" ]
        env:
        # namespace to watch 
        # recommend to be the same with the one aranya deployed to
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "aranya"
        volumeMounts:
        - name: config
          mountPath: /etc/aranya
        resources:
          limits:
            memory: "200Mi"
