---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aranya
  namespace: edge
data:
  config.yaml: |-
    controller:
      log:
        level: 5
        dir: /var/log/aranya/

    virtualnode:
      connectivity:
        # this is the virtual node behavior definition for all EdgeDevices
        # EdgeDevice's spec can override some of these fields
        timers:
          # force close session in server after
          unary_session_timeout: 1m
          # force sync node status from edge device after
          force_node_status_sync_interval: 10m
          # force sync pod status from edge device after
          force_pod_status_sync_interval: 10m
      # node status manager
      node:
        timers:
          # should be consistent with your cluster config
          status_sync_interval: 10s
      # pod status manager and scheduler
      pod:
        timers:
          # interval pod informer to resync cached pods
          resync_interval: 60s
      # http streams (started by kubectl commands)
      stream:
        timers:
          # close stream when no traffic has been sent/recv for
          # (kubelet default is 4h)
          idle_timeout: 30m
          # cancel stream creation after
          # (kubelet default is 30s)
          creation_timeout: 30s

    services:
      metrics:
        # set to empty string to disable
        address: ""
        port: 8383

---
# this is an example deployment script for test deployment only
# use StatefulSet if possible
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aranya
  namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aranya
      arhat.dev/role: Controller
  template:
    metadata:
      labels:
        name: aranya
        # required label to get gRPC services working
        arhat.dev/role: Controller
    spec:
      serviceAccountName: aranya
      # required to work in host network mode to serve kubelet http service
      hostNetwork: true
      volumes:
      - name: config
        configMap:
          name: aranya
          optional: true
      containers:
      - name: aranya
        image: arhatdev/aranya:latest
        imagePullPolicy: Always
        command: [ "/app" ]
        env:
        # The namespace aranya deployed to
        # if not set, will be `default`
        - name: ARANYA_NAMESPACE
          # the value of this environment variable MUST be the
          # namespace name aranya deployed to, or aranya won't work properly
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # The namespace `aranya` to watch
        # if not set, will default to be the same with ARANYA_NAMESPACE
        - name: WATCH_NAMESPACE
          # in most case, this should the same with `ARANYA_NAMESPACE`
          # but for multi-tenant edge device management in single cluster
          # this can be set to another namespace aranya not deployed to
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # the pod name aranya running in
        # used to find the node aranya running in
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "aranya"
        volumeMounts:
        - name: config
          mountPath: /etc/aranya
        resources:
          limits:
            # "100Mi" is sufficient for about 300 edge devices (with small workloads)
            memory: "100Mi"
