---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aranya
  namespace: edge
rules:
- apiGroups: [""] # core resources
  resources:
  # to expoese metric service and gRPC service
  - services
  # to fetch configmaps required by pod for edge devices
  # and leader election lock
  - configmaps
  # to fetch secrets required by pods for edge devices
  - secrets
  # to watch pods change and deliver command to edge devices
  - pods
  # to update pods status according to edge devices messages
  - pods/status
  verbs: ["*"]
# control aranya crds
- apiGroups: ["aranya.arhat.dev"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aranya
rules:
- apiGroups: [""]
  resources:
  # to create virtual node and get node object aranya lives in
  - nodes
  # to update virtual node status according to edge devices messages
  - nodes/status
  verbs: ["*"]
# required to generate node certificates automatically
- apiGroups:
  - certificates.k8s.io
  resources:
  # to create kubernetes csr for virtual node certs
  - certificatesigningrequests
  # To automatically approve kubernetes csrs created by aranya
  # remove the approval ability if you would like to
  # approve on you own (for security reason)
  - certificatesigningrequests/approval
  verbs: ["*"]

# TODO: find a way to create cluster role binding in script with different namespace

# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: aranya
#   namespace: edge
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: aranya
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: aranya
# subjects:
# - kind: ServiceAccount
#   name: aranya
#   namespace: edge