apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: edgedevices.aranya.arhat.dev
spec:
  group: aranya.arhat.dev
  names:
    kind: EdgeDevice
    listKind: EdgeDeviceList
    plural: edgedevices
    singular: edgedevice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            certInfo:
              properties:
                country:
                  type: string
                state:
                  type: string
                locality:
                  type: string
                org:
                  type: string
                orgUnit:
                  type: string
            connectivity:
              properties:
                method:
                  type: string
                grpcConfig:
                  properties:
                    server:
                      type: string
                    tlsSecretRef:
                      type: object
                mqttConfig:
                  properties:
                    broker:
                      type: string
                    tlsSecretRef:
                      type: object
                    transport:
                      type: string
                    version:
                      type: string
                    messageNamespace:
                      type: string
                    connectPacket:
                      properties:
                        cleanSession:
                          type: boolean
                        clientID:
                          type: string
                        keepalive:
                          format: int32
                          type: integer
                        password:
                          type: object
                        username:
                          type: string
                        will:
                          type: boolean
                        willMessage:
                          type: string
                        willQos:
                          format: int32
                          type: integer
                        willRetain:
                          type: boolean
                        willTopic:
                          type: string
        status:
          properties: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
