// +build !ignore_autogenerated

/*
aranya Authors
*/

// Code generated by kube-openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/aranya/v1alpha1/.EdgeDevice":       schema_apis_aranya_v1alpha1__EdgeDevice(ref),
		"./pkg/apis/aranya/v1alpha1/.EdgeDeviceSpec":   schema_apis_aranya_v1alpha1__EdgeDeviceSpec(ref),
		"./pkg/apis/aranya/v1alpha1/.EdgeDeviceStatus": schema_apis_aranya_v1alpha1__EdgeDeviceStatus(ref),
	}
}

func schema_apis_aranya_v1alpha1__EdgeDevice(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "EdgeDevice is the Schema for the edgedevices API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/aranya/v1alpha1/.EdgeDeviceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/aranya/v1alpha1/.EdgeDeviceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/aranya/v1alpha1/.EdgeDeviceSpec", "./pkg/apis/aranya/v1alpha1/.EdgeDeviceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_apis_aranya_v1alpha1__EdgeDeviceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "EdgeDeviceSpec defines the desired state of EdgeDevice",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"connectivity": {
						SchemaProps: spec.SchemaProps{
							Description: "Connectivity designate the method by which this device connect to aranya server",
							Ref:         ref("./pkg/apis/aranya/v1alpha1/.Connectivity"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/aranya/v1alpha1/.Connectivity"},
	}
}

func schema_apis_aranya_v1alpha1__EdgeDeviceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "EdgeDeviceStatus defines the observed state of EdgeDevice",
				Type:        []string{"object"},
			},
		},
	}
}
