apiVersion: v1
kind: Pod
metadata:
  name: example-edge-pod
spec:
  tolerations:
    # set deploy to which virtual cluster (kubernetes namespace)
    # this toleration is requeired, because it's the taint set on every node in that virtual cluster
    - key: arhat.dev/namespace
      operator: Equal
      value: edge
    - key: node.kubernetes.io/unreachable
      operator: Exists
  nodeSelector:
    # select specific remote node(s) with labels
    arhat.dev/role: node
    arhat.dev/name: example-edge-device-grpc
  containers:
  - name: sleep
    image: alpine:latest
    command:
    - /bin/sleep
    - "3600"
  restartPolicy: Never
